---
title: "GCA手动_1"
author: "Chen Xing"
date: '2022-05-18'
output: html_document
---

## 摘要
手动gca

### 必要的包
```{r, message=FALSE, warning=FALSE, results='hide', echo=FALSE}
library(tidyverse)
library(lmerTest)
library(parameters)
library(effectsize)
library(emmeans)
library(performance)
library(sjPlot)
library(ggpubr)
library(rstatix)
library(furrr)
plan(multisession, workers = 6)
```

### 读取数据
```{r, message=FALSE, warning=FALSE}
dt <- read_csv("/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/ea/data/raw_time_b3.gz")

dt2 <- dt %>% group_by(Target, participant_phone, Time, AOI) %>%
  summarise(sample=sum(SamplesInAOI, rm.na=T),  N=sum(SamplesTotal), Elog=mean(Elog, rm.na=T), Prop=mean(Prop,rm.na=T)) %>% mutate(nelog=log((sample + .5) / (N - sample + .5)))

tlist <- unique(dt2$Time)
alist <- unique(dt2$AOI)

cl <- function(dt, time, metri){
  dts <- filter(dt, Time==time) %>% drop_na(!!sym(metri)) %>% ungroup() %>%
    select(!!sym(metri))
  
  
  l <- shapiro.test(dts[,1][[1]])[2][[1]]
}

cl2 <- function(dt, aoi, metri){
  dts <- filter(dt, AOI==aoi) %>% drop_na()
  future_map(tlist, cl, dt=dts, metri=metri)
}


cl3 <- function(dt, metri){
  dts <- dt
  future_map(alist, cl2, dt=dts, metri=metri)
}



metri <- "sample"

dttt <- dt2 %>% filter(AOI=="b3_ne")

dts <- filter(dttt, Time==100) %>% drop_na(!!sym(metri)) %>% ungroup() %>%
  select(!!sym(metri))


l <- shapiro.test(dts[,1][[1]])[2][[1]]


cl(dttt, 100, "sample")

shapiro.test(dttt$sample)

a <- cl3(dt2, "sample")
b <- cl3(dt2, "Prop")
c <- cl3(dt2, "Elog")
d <- cl3(dt2, "nelog")
```


### 开始gca
```{r, message=FALSE, warning=FALSE}
dt3 <- dt

dt3$AOI <- as.factor(dt3$AOI)
dt3$Target <- as.factor(dt3$Target)


dt3 <- dt3 %>% select(-c('ot1','ot2','ot3','ot4','ot5','ot6','ot7'))

# 针对timezone对数据进行切割
dt3_1 <- dt3 %>% filter(between(Time,0,8600))
dt3_2 <- dt3 %>% filter(between(Time,8600,17700)) %>% mutate(Time=Time-8600)
dt3_3 <- dt3 %>% filter(between(Time,17700,30000)) %>% mutate(Time=Time-17700)





time_code_m <- function(dt3){
  dt3 <- dt3 %>% group_by(participant_phone,trial_id, AOI,TimeBin) %>%
    summarise(Prop=mean(Prop, rm.na=T), y= sum(SamplesInAOI), N = sum(SamplesTotal), Time=min(Time)) %>%
    mutate(Elog = log( (y+.5) / (N-y+.5) )) %>% ungroup()
  
  orthogonal_polynomials <- poly(sort(as.vector(unique(dt3$Time))), 5)
  
  ggplot(data.frame(orthogonal_polynomials), aes(x=X1, y=X1)) +
                 geom_point() +
                 geom_point(aes(y=X2), color='red') +  
                 geom_point(aes(y=X3), color='blue') +
                 geom_point(aes(y=X4), color='green') +
                 geom_point(aes(y=X5), color='purple')
  
  time_codes <- data.frame(
                          sort(as.vector(unique(dt3$Time))),
                          orthogonal_polynomials[, c(1:5)]
                        )
  colnames(time_codes) <- c('Time','ot1','ot2','ot3','ot4','ot5')
  
  dt3 <- full_join(dt3, time_codes)
}

dt3_1 <- time_code_m(dt3_1)
dt3_2 <- time_code_m(dt3_2)
dt3_3 <- time_code_m(dt3_3)


model.base <- lmer(Elog ~ (ot1+ot2+ot3+ot4) + (1| participant_phone), data = dt3_3)
model.0 <- lmer(Elog ~ (ot1+ot2+ot3+ot4)+AOI + (1| participant_phone), data = dt3_3)
model.1 <- lmer(Elog ~ (ot1+ot2+ot3+ot4)+AOI+ot1*AOI + (1| participant_phone), data = dt3_3)
model.2 <- lmer(Elog ~ (ot1+ot2+ot3+ot4)+AOI+(ot1+ot2)*AOI + (1| participant_phone), data = dt3_3)
model.3 <- lmer(Elog ~ (ot1+ot2+ot3+ot4)+AOI+(ot1+ot2+ot3)*AOI + (1| participant_phone), data = dt3_3)
model.4 <- lmer(Elog ~ (ot1+ot2+ot3+ot4)*AOI + (1| participant_phone), data = dt3_3)

anova(model.base, model.0, model.1, model.2, model.3, model.4)

summary(model.4)
performance(model)
drop1(model)



ggplot(dt3_3, aes(x=Time, y=Elog, color=AOI)) +
                     stat_summary(fun.data=mean_se, geom="pointrange",alpha=0.75, size=0.3) +
                     stat_summary(aes(y=predict(model.4,dt3_3,re.form=NA)), fun.y=mean, geom="line")

```