---
title: "b3时序整体分析2"
author: "Chen Xing"
date: '2022-05-17'
output: html_document
---

## 摘要
对整体时序数据进行探索分析,使用重复测量方差分析进行时间点差异检验

### 必要的包
```{r, message=FALSE, warning=FALSE, results='hide', echo=FALSE}
library(tidyverse)
library(lmerTest)
library(parameters)
library(effectsize)
library(emmeans)
library(performance)
library(sjPlot)
library(ggpubr)
library(rstatix)
```


### 读取时序数据
```{r, message=FALSE, warning=FALSE}
# 读取文件
dt <- read_csv("/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/ea/data/raw_time_b3.gz")

dt2 <- dt %>% mutate(participant_phone=as.factor(participant_phone), trial_id=as.factor(trial_id), Time=as.factor(Time)) %>% group_by(participant_phone, AOI, Time) %>%
  summarise(dv=mean(SamplesInAOI,rm.na=T)) %>% ungroup()


res.aov <- anova_test(data = dt2, dv = dv, wid = participant_phone, within = c(AOI, Time))
get_anova_table(res.aov)

one.way <- dt2 %>%
  group_by(Time) %>%
  anova_test(dv = dv, wid = participant_phone, within = AOI) %>%
  get_anova_table() %>%
  adjust_pvalue(method = "bonferroni")

pwc <- dt2 %>%
  group_by(Time) %>%
  pairwise_t_test(
    dv ~ AOI, paired = TRUE,
    p.adjust.method = "bonferroni"
    )
pwcf <- pwc %>% filter(p.adj.signif!="ns")


sha <- dt2 %>%
  group_by(AOI, Time) %>%
  shapiro_test(dv) %>% filter(p<0.05)

# 统计整体时序数据
oval <- dt %>% group_by(AOI, Time) %>%
  summarise(gn = mean(SamplesInAOI, na.rm=T) ,prop = mean(Prop, na.rm=T))

# 统计高特质正念数据
low <- dt %>% filter(Target=="low") %>%
  group_by(AOI, Time) %>%
  summarise(gn = mean(SamplesInAOI, na.rm=T) ,prop = mean(Prop, na.rm=T))

# 统计z中特质正念数据
mid <- dt %>% filter(Target=="mid") %>%
  group_by(AOI, Time) %>%
  summarise(gn = mean(SamplesInAOI, na.rm=T) ,prop = mean(Prop, na.rm=T))

# 统计低特质正念数据
high <- dt %>% filter(Target=="high") %>%
group_by(AOI, Time) %>%
  summarise(gn = mean(SamplesInAOI, na.rm=T) ,prop = mean(Prop, na.rm=T))
```


### 数据可视化
```{r, message=FALSE, warning=FALSE}
# 整体
ggplot(oval, aes(x = Time,
                     y = gn)) +
  geom_line(aes(col = AOI),size = 1.0 ) +
  scale_color_brewer(palette = "Set2")

# 高特质正念
ggplot(low, aes(x = Time,
                 y = gn)) +
  geom_line(aes(col = AOI),size = 1.0 ) +
  scale_color_brewer(palette = "Set2")

# 中特质正念
ggplot(mid, aes(x = Time,
                 y = gn)) +
  geom_line(aes(col = AOI),size = 1.0 ) +
  scale_color_brewer(palette = "Set2")

# 低特质正念
ggplot(high, aes(x = Time,
                y = gn)) +
  geom_line(aes(col = AOI),size = 1.0 ) +
  scale_color_brewer(palette = "Set2")
```


### 数据可视化
```{r, message=FALSE, warning=FALSE}
# 整体
ggplot(oval, aes(x = Time,
                     y = prop)) +
  geom_smooth(aes(col = AOI),size = 1.5 ) +
  scale_color_brewer(palette = "Set2")

# 高特质正念
ggplot(low, aes(x = Time,
                 y = prop)) +
  geom_smooth(aes(col = AOI),size = 1.5 ) +
  scale_color_brewer(palette = "Set2")

# 中特质正念
ggplot(mid, aes(x = Time,
                 y = prop)) +
  geom_smooth(aes(col = AOI),size = 1.5 ) +
  scale_color_brewer(palette = "Set2")


# 低特质正念
ggplot(high, aes(x = Time,
                y = prop)) +
  geom_smooth(aes(col = AOI),size = 1.5 ) +
  scale_color_brewer(palette = "Set2")
```
