---
title: "Time_bin_mixed"
author: "Chen Xing"
date: '2022-05-18'
output: html_document
---

## 摘要
针对注视比例出时序图并进行mixed模型差异分析

### 必要的包
```{r, message=FALSE, warning=FALSE, results='hide', echo=FALSE}
library(tidyverse)
library(lmerTest)
library(emmeans)
library("ggplot2")
library("gridExtra")
library(viridis)
library(ggthemes)
library(cowplot)
```

### 读取数据初步时序图
```{r, message=FALSE, warning=FALSE}
dt <- read_csv("/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/ea/data/raw_time_b3.gz") %>%
  select(1:7,10,13)

dt2 <- dt %>% group_by(participant_phone, AOI, Time) %>%
  summarise(Prop=mean(Prop, rm.na=T))

ggplot(dt2, aes(x=Time, y=Prop, color=AOI)) +
  stat_summary(fun.y=mean, geom="point")
```


### 混合模型数据准备,初步进行各个时间段两两对比
```{r, message=FALSE, warning=FALSE}
dt3 <- dt
dt4 <- dt2

# 对AOI因子重新编码
dt3$AOI <- factor(dt3$AOI, levels=c("b3_ne", "b3_pos", "b3_neg", "b3_thr"))
contrasts(dt3$AOI) = contr.sum(4)

dt4$AOI <- factor(dt4$AOI, levels=c("b3_ne", "b3_pos", "b3_neg", "b3_thr"))
contrasts(dt4$AOI) = contr.sum(4)



mm2 <- function(dt, t){
  dt4 <- dt %>% filter(Time==t)
  model <- lmer(Prop ~ AOI  + (1| participant_phone) + (1| participant_phone:AOI) + (1|trial_id),  data = dt4)
  
  pwc <- summary(pairs(emmeans(model, "AOI", lmerTest.limit = 10000))) %>% filter(p.value <0.05) %>%
    mutate(Time=t)
  pwc
}

tlist <- unique(dt4$Time)

k2 <- bind_rows(map(tlist, mm2, dt=dt3))

k3 <- k2 %>% filter(p.value<(0.05/300))

k3 <- k3 %>% rowwise() %>%
  mutate(A1=str_split_fixed(contrast, " - ",2)[[1]], A2=str_split_fixed(contrast, " - ",2)[2]) %>%
  mutate(Big=case_when(estimate>0~A1,
                       estimate<0~A2),
         Small=case_when(estimate>0~A2,
                       estimate<0~A1))


rankc <- function(dt, aoi){
  dt[[aoi]] <- sum(aoi == dt$Small)+1
  dt
}


rankc2 <- function(dt, time){
  dt <- dt %>% filter(Time==time)
  alist <- append(unique(dt$Big), unique(dt$Small))
  reduce((map(alist, rankc, dt=dt)), full_join)
}

rankc3 <- function(dt){
  tblist <- unique(dt$Time)
  reduce((map(tblist, rankc2, dt=dt)), full_join)
}

nk <- rankc3(k3)

write_csv(nk, "/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/ea/data/b3_timec_pwc.csv")

nk2 <- nk  %>% select(Time, b3_pos, b3_neg, b3_thr, b3_ne) %>%
  distinct() %>% pivot_longer(2:5, names_to = "AOI", values_to = "rank")

stdrank <- function(t, dt){
  dt$rank2 <- scale(dt$rank, center = T)[,1]
  dt$ranksum <- sum(dt$rank2, na.rm = T)
  dt
}

nnk2 <- bind_rows(map(unique(nk2$Time), stdrank, dt=nk2)) %>% distinct() %>%
  mutate(rankstd=rank2/ranksum)


```


### 进行叠加可视化
```{r, message=FALSE, warning=FALSE}
dt_v <- full_join(dt2, nnk2) %>%
  mutate(rank=factor(rank, levels=c(1,2,3,4)))

dt_rank <- dt_v %>% group_by(Time, AOI) %>%
  mutate(rank=as.numeric(rank)) %>%
  summarise(rank=mean(rank, na.rm=T))

p3 <- ggplot(dt_rank, aes(x=Time, y=AOI, fill=rank)) +
  geom_raster() + scale_fill_viridis() +
  theme_tufte(base_family="Helvetica") +
  theme(axis.ticks=element_blank(), axis.text.x=element_blank(),axis.title.x=element_blank(),
        plot.margin=unit(c(1,1,-0.35,1), "cm"))


p2 <- ggplot(dt_v, aes(x=Time, y=Prop,color=AOI, fill=AOI, shape=rank)) +
  scale_shape_manual(values=c(21:24))+
  stat_summary(fun.y=mean, geom="point", size=2, alpha = 0.35) +
  theme(legend.key.size = unit(5, "pt"), legend.position = "right")

p1 <- ggplot(dt_v, aes(x=Time, y=Prop, color=AOI)) +
  stat_summary(fun.y=mean, geom="line", size=1, alpha = 0.75) +
  theme(legend.key.size = unit(5, "pt"), legend.position = "right",
        axis.text.x=element_blank(),axis.title.x=element_blank())

p4 <- ggplot(dt_v, aes(x=Time, y=Prop, color=AOI)) +
  stat_summary(fun.y=mean, geom="line", size=1, alpha = 0.75) +
  theme(legend.key.size = unit(5, "pt"), legend.position = "right",
        plot.margin=unit(c(0,1,1,1), "cm"))

p1_npg = p1 + ggsci::scale_color_npg()
p2_npg = p2 + ggsci::scale_color_npg()
p3_npg = p3
p4_npg = p4 + ggsci::scale_color_npg()
grid.arrange(p1_npg, p2_npg, ncol = 1, nrow=2)
plot_grid(p3, p4_npg, ncol = 1, align = "v",rel_heights = c(1, 2), label_size= c(1,10))
```


### 进行时序区间划分
```{r, message=FALSE, warning=FALSE}
timezone <- nk %>% group_by(Time) %>%
  summarise(pairsn = n())

timezone %>% rowwise() %>%
  mutate(inter=diff(Time))

timezone$inter <- append(diff(timezone$Time),0)

t <- timezone %>% filter(inter>1000)

```