---
title: "数据清洗"
author: "Chen Xing"
date: '2022-04-11'
output: html_document
---
```{r, echo=FALSE}
library(tidyverse)
library(readxl)
library(data.table)
```

## 1. 排出眼动数据缺失被试
```{r}
dt <- read_csv("/Users/placenameday/R study/edf_demo/para/para_data/数据核对表.csv")
check <- read_excel("/Users/placenameday/R study/edf_demo/para/para_data/check_list.xlsx") %>% rename(participant_phone=phone) %>% mutate(participant_phone=as.numeric(participant_phone))

queshi <- anti_join(check,dt) %>% mutate(reason="眼动缺失")
queshi
```
1042,3018,4027无眼动数据

## 2. 列出重复被试
```{r}
chongfu <- check[which(duplicated(check$participant_phone)),]
chongfu <- full_join(chongfu,check[which(check$participant_phone==18220577603),]) %>% mutate(reason="重复数据")
chongfu
```
1007，1028重复，删除1028

## 3. 剔除眼动数据有效率过低被试
```{r, message=FALSE, warning=FALSE}
# 定义函数 计算有效眼动数据比例
vali_eye <- function(rawd){
  dt <- fread(rawd) %>%
    mutate(wuxiao=if_else((xp==0&yp==0)|(is.na(xp)&is.na(yp)), 1,0), youxiao=if_else((xp==0&yp==0)|(is.na(xp)&is.na(yp)), 0,1)) %>%
    group_by(participant_group, participant_phone, block_name) %>%
    summarise(vali=sum(youxiao)/(sum(youxiao)+sum(wuxiao)))
}

ve_c <- function(dic){
  file_list <- paste(dic,"/",list.files(dic), sep = "")
  ilist <- map(file_list, vali_eye)
  bind_rows(ilist)
}

youxiao <- ve_c("/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/tidy/raw")
```

```{r}
wx <- group_by(youxiao, participant_phone) %>% summarise(vali_m=mean(vali)) %>%
  mutate(participant_phone=as.numeric(participant_phone)) %>%
  filter(vali_m<0.70) %>% left_join(check) %>%
  select(name, "participant id", participant_phone, group) %>% filter(!is.na(name)) %>% mutate(reason="眼动不足")
wx
```

## 4. 提取排除列表
```{r}
pc <- full_join(queshi, chongfu) %>% full_join(wx)
pc
write_excel_csv(pc, "/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/tidy/paichu.csv")
```