---
title: "data_cleanning_aoi_2"
author: "Chen Xing"
date: '2022-04-19'
output: html_document
---

# 根据具体刺激生成的AOI区域对数据进行aoi打标 2
用R进行大量运算速度较慢，建议改用python进行

## 必要的包
```{r, message=FALSE, warning=FALSE, results='hide'}
library(tidyverse)
library(data.table)
library(furrr)
library(progress)
plan(multisession, workers = 4)
```

## 整合所有aoi信息
```{r, message=FALSE, warning=FALSE}
aoi_dir <- "/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/tidy/AOI_info/"
aoi_list <- list.files(aoi_dir)

# 定义aoi文件信息整理方法
std_aoi <- function(file){
  aoi_name <- str_split_fixed(file, "\\.",2)[1]
  aoi_info <- read_csv(paste(aoi_dir, file, sep = "")) %>%
    filter(!is.null(Left)) %>%
    mutate(aoi_name=aoi_name) %>%
    select(block_name, stim_name, aoi_name, Left, Top, Right, Bottom) %>%
    rename(trial_name=stim_name)
}

# 整合aoi文件
aoi_info <- reduce(map(aoi_list, std_aoi),full_join) %>% filter(!is.na(Left))
write_excel_csv(aoi_info, "/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/tidy/AOI_info.csv")

```

## 定义打标方法
```{r, message=FALSE, warning=FALSE}


# 定义判断是否落入AOI方法
aj <- function(n, l, t, r, b, dt, xp=xp, yp=yp) {
    dt[[n]] <- with(dt, if_else((l<xp&xp<r)&(t<yp&yp<b),TRUE,FALSE))
    dt
}

# 定义单个trialAOI判断与汇总方法
trial_name_aoi <- function(trial_n, ai = aoi_info, f = file, pb){
  pb$tick()$print()
  aoi_trial_info <- filter(ai, trial_name==trial_n)
  trial_file <- filter(f, trial_name==trial_n)
  suppressMessages(reduce(future_pmap(list(aoi_trial_info$aoi_name, aoi_trial_info$Left, aoi_trial_info$Top, aoi_trial_info$Right, aoi_trial_info$Bottom), aj, dt=trial_file),suppressMessages(full_join)))
}

# 定义单个个体AOI判断与汇总方法
sub_aoi <- function(f_path, out_path, a_path, pb2){
  pb2$tick()$print()
  file <- fread(f_path)
  aoi <- fread(a_path)
  trial_list <- unique(file$trial_name)
  pb <- progress_estimated(length(trial_list))
  new <- suppressMessages(reduce(map(trial_list, trial_name_aoi, ai=aoi, f=file,pb=pb), suppressMessages(full_join)))
  write_csv(new, file=gzfile(out_path))
}

# 定义单个目录的AOI批量判断
mul_aoi <- function(in_dir, out_dir){
  if (!dir.exists(out_dir)) {
    dir.create(out_dir)
  }
  out_list <- paste(out_dir,"/",list.files(in_dir), ".gz", sep = "")
  in_list <- paste(in_dir,"/",list.files(in_dir), sep = "")
  a_path <- "/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/tidy/AOI_info.csv"
  pb2 <- progress_estimated(length(in_list))
  map2(in_list, out_list, sub_aoi, a_path=a_path, pb2=pb2)
}

```
## 运行函数进行打标并保存
设定输入文件夹`raw_d <- "/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/tidy/raw_clean"`   
设定输出文件夹`raw_o <- "/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/tidy/raw_aoi"`   
运行函数`mul_aoi(raw_d,raw_o)`   
用同样方法对eye_event数据进行打标，注意修改xp与yp名称
