---
title: "b2_ana_2"
author: "Chen Xing"
date: '2022-05-06'
output:
  html_document: default
  word_document: default
  pdf_document: default
---

## 开始分析 gaze 与量表的关系

### 必要的包
```{r, message=FALSE, warning=FALSE, results='hide', echo=FALSE}
library(tidyverse)
library(rstatix)
library(ggpubr)
library(lmerTest)
library(sjPlot)
library(parameters)
library(effectsize)
library(emmeans)
library(performance)
```


#### 参数定义
```{r, message=FALSE, warning=FALSE}
bname <- c("b2")
sname <- 1
a <- c("b2_sp", "b2_jj", "b2_xj", "b2_n", "b2_center")
metri <- c("gaze")
dt <- read_csv("/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/ea/data/b2_info.csv")
```

#### fangfa
```{r, message=FALSE, warning=FALSE}
# 数据准备
dtc2 <- dt %>% filter(block_name==bname, stim==sname, AOI %in% a) %>%
  group_by(participant_phone, AOI) %>%
  summarise(fc=mean(!!sym(metri), na.rm=T), maas=mean(maas), tgjl=mean(tgjl), sas=mean(sas)) %>%
  filter(!is.na(fc)) %>%
  mutate(AOI=case_when(AOI == "b2_sp"~"sp",
                       AOI == "b2_jj"~"pos",
                       AOI == "b2_xj"~"neg",
                       AOI == "b2_n"~"ne",
                       AOI == "b2_star"~"star",
                       AOI == "b2_no_star"~"no_star",
                       AOI == "b2_center"~"center")) %>%
  ungroup() %>%
  convert_as_factor(participant_phone, AOI) %>%
  select(participant_phone, AOI, tgjl, maas, sas, fc)


# 极端值处理
outdata <- dtc2 %>%
  group_by(AOI) %>%
  identify_outliers(fc)
dtb3_r <- anti_join(dtc2, outdata)
outdata2 <- dtb3_r %>%
  group_by(AOI) %>%
  identify_outliers(fc)
dtb3_r2 <- anti_join(dtb3_r, outdata2)
outdata3 <- dtb3_r2 %>%
  group_by(AOI) %>%
  identify_outliers(fc)
dtb3_r3 <- anti_join(dtb3_r2, outdata3)
outdata4 <- dtb3_r3 %>%
  group_by(AOI) %>%
  identify_outliers(fc)
dtb3_r4 <- anti_join(dtb3_r3, outdata4)
outdata5 <- dtb3_r4 %>%
  group_by(AOI) %>%
  identify_outliers(fc)


# 模型拟合
mixed_maas = lmer(fc ~ maas+AOI+maas*AOI + (1 | participant_phone), data = dtb3_r4)
mixed_sas = lmer(fc ~ sas*AOI + (1 | participant_phone), data = dtb3_r4)
mixed_two = lmer(fc ~ maas+sas+AOI+maas*sas+maas*AOI+sas*AOI + (1 | participant_phone), data = dtb3_r4)

# maas 结果
# 基本参数
model_parameters(mixed_maas)
model_performance(mixed_maas)
anova(mixed_maas)
eta_squared(mixed_maas)
# 简单效应与配对检验
maas_emm <- emmeans(mixed_maas, pairwise ~ AOI | maas, cov.reduce = function(x) quantile(x, c(0.1, 0.3, 0.5, 0.7,0.9)))
maas_emm
joint_tests(mixed_maas , by=c("AOI"))
joint_tests(mixed_maas , by=c("maas"), cov.reduce = function(x) quantile(x, c(0.1, 0.3, 0.5, 0.7,0.9)))
contrast(maas_emm, "consec", simple = "each", combine = TRUE, adjust = "mvt")
# 交互作用可视化
emmip(mixed_maas, maas ~ AOI, mult.name = "variety", cov.reduce = FALSE)
# 模型固定因子效应量
plot_model(mixed_maas, show.values = TRUE, value.offset = .3, title = metri)
# 模型交互1
plot_model(mixed_maas, type = "pred", terms = c("maas", "AOI"), title = metri, axis.title = metri)
# 模型交互2
 plot_model(mixed_maas, type = "pred", terms = c("AOI", "maas"), title = metri, axis.title = metri)


# sas 结果
model_parameters(mixed_sas)
model_performance(mixed_sas)
anova(mixed_sas)
eta_squared(mixed_sas)
# 简单效应与配对检验
sas_emm <- emmeans(mixed_sas, pairwise ~ AOI | sas, cov.reduce = function(x) quantile(x, c(0.1, 0.3, 0.5, 0.7,0.9)))
sas_emm
joint_tests(mixed_sas , by=c("AOI"))
joint_tests(mixed_sas , by=c("sas"), cov.reduce = function(x) quantile(x, c(0.1, 0.3, 0.5, 0.7,0.9)))
contrast(sas_emm, "consec", simple = "each", combine = TRUE, adjust = "mvt")
# 交互作用可视化
emmip(mixed_sas, sas ~ AOI, mult.name = "variety", cov.reduce = FALSE)
# 模型固定因子效应量
plot_model(mixed_sas, show.values = TRUE, value.offset = .3, title = metri)
# 模型交互1
plot_model(mixed_sas, type = "pred", terms = c("sas", "AOI"), title = metri, axis.title = metri)
# 模型交互2
plot_model(mixed_sas, type = "pred", terms = c("AOI", "sas"), title = metri, axis.title = metri)

  
```


#### 参数定义
```{r, message=FALSE, warning=FALSE}
bname <- c("b2")
sname <- 2
a <- c("b2_star", "b2_no_star", "b2_center")
metri <- c("gaze")
dt <- read_csv("/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/ea/data/b2_info.csv")
```

#### fangfa
```{r, message=FALSE, warning=FALSE}
# 数据准备
dtc2 <- dt %>% filter(block_name==bname, stim==sname, AOI %in% a) %>%
  group_by(participant_phone, AOI) %>%
  summarise(fc=mean(!!sym(metri), na.rm=T), maas=mean(maas), tgjl=mean(tgjl), sas=mean(sas)) %>%
  filter(!is.na(fc)) %>%
  mutate(AOI=case_when(AOI == "b2_sp"~"sp",
                       AOI == "b2_jj"~"pos",
                       AOI == "b2_xj"~"neg",
                       AOI == "b2_n"~"ne",
                       AOI == "b2_star"~"star",
                       AOI == "b2_no_star"~"no_star",
                       AOI == "b2_center"~"center")) %>%
  ungroup() %>%
  convert_as_factor(participant_phone, AOI) %>%
  select(participant_phone, AOI, tgjl, maas, sas, fc)


# 极端值处理
outdata <- dtc2 %>%
  group_by(AOI) %>%
  identify_outliers(fc)
dtb3_r <- anti_join(dtc2, outdata)
outdata2 <- dtb3_r %>%
  group_by(AOI) %>%
  identify_outliers(fc)
dtb3_r2 <- anti_join(dtb3_r, outdata2)
outdata3 <- dtb3_r2 %>%
  group_by(AOI) %>%
  identify_outliers(fc)
dtb3_r3 <- anti_join(dtb3_r2, outdata3)
outdata4 <- dtb3_r3 %>%
  group_by(AOI) %>%
  identify_outliers(fc)
dtb3_r4 <- anti_join(dtb3_r3, outdata4)
outdata5 <- dtb3_r4 %>%
  group_by(AOI) %>%
  identify_outliers(fc)


# 模型拟合
mixed_maas = lmer(fc ~ maas+AOI+maas*AOI + (1 | participant_phone), data = dtb3_r4)
mixed_sas = lmer(fc ~ sas*AOI + (1 | participant_phone), data = dtb3_r4)
mixed_two = lmer(fc ~ maas+sas+AOI+maas*sas+maas*AOI+sas*AOI + (1 | participant_phone), data = dtb3_r4)

# maas 结果
# 基本参数
model_parameters(mixed_maas)
model_performance(mixed_maas)
anova(mixed_maas)
eta_squared(mixed_maas)
# 简单效应与配对检验
maas_emm <- emmeans(mixed_maas, pairwise ~ AOI | maas, cov.reduce = function(x) quantile(x, c(0.1, 0.3, 0.5, 0.7,0.9)))
maas_emm
joint_tests(mixed_maas , by=c("AOI"))
joint_tests(mixed_maas , by=c("maas"), cov.reduce = function(x) quantile(x, c(0.1, 0.3, 0.5, 0.7,0.9)))
contrast(maas_emm, "consec", simple = "each", combine = TRUE, adjust = "mvt")
# 交互作用可视化
emmip(mixed_maas, maas ~ AOI, mult.name = "variety", cov.reduce = FALSE)
# 模型固定因子效应量
plot_model(mixed_maas, show.values = TRUE, value.offset = .3, title = metri)
# 模型交互1
plot_model(mixed_maas, type = "pred", terms = c("maas", "AOI"), title = metri, axis.title = metri)
# 模型交互2
 plot_model(mixed_maas, type = "pred", terms = c("AOI", "maas"), title = metri, axis.title = metri)


# sas 结果
model_parameters(mixed_sas)
model_performance(mixed_sas)
anova(mixed_sas)
eta_squared(mixed_sas)
# 简单效应与配对检验
sas_emm <- emmeans(mixed_sas, pairwise ~ AOI | sas, cov.reduce = function(x) quantile(x, c(0.1, 0.3, 0.5, 0.7,0.9)))
sas_emm
joint_tests(mixed_sas , by=c("AOI"))
joint_tests(mixed_sas , by=c("sas"), cov.reduce = function(x) quantile(x, c(0.1, 0.3, 0.5, 0.7,0.9)))
contrast(sas_emm, "consec", simple = "each", combine = TRUE, adjust = "mvt")
# 交互作用可视化
emmip(mixed_sas, sas ~ AOI, mult.name = "variety", cov.reduce = FALSE)
# 模型固定因子效应量
plot_model(mixed_sas, show.values = TRUE, value.offset = .3, title = metri)
# 模型交互1
plot_model(mixed_sas, type = "pred", terms = c("sas", "AOI"), title = metri, axis.title = metri)
# 模型交互2
plot_model(mixed_sas, type = "pred", terms = c("AOI", "sas"), title = metri, axis.title = metri)

  
```
