---
title: "b1_ana_6"
author: "Chen Xing"
date: '2022-05-07'
output:
  html_document: default
  word_document: default
  pdf_document: default
---

## 对b3进行 针对性分析 对问题

### 必要的包
```{r, message=FALSE, warning=FALSE, results='hide', echo=FALSE}
library(tidyverse)
library(rstatix)
library(ggpubr)
library(lmerTest)
library(sjPlot)
library(parameters)
library(effectsize)
library(emmeans)
library(performance)
```


### 开始分析
#### 数据准备
```{r, message=FALSE, warning=FALSE}
# 数据导入
dt <- read.csv("/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/ea/data/inner_dt_aoi_re.csv")
```

#### fangfa
```{r, message=FALSE, warning=FALSE}
mix_e_f <- function(dt, bname, sname, a, metri){
  # 数据准备
  dtc2 <- dt %>% filter(block_name %in% bname, stim %in% sname, AOI %in% a) %>%
    group_by(participant_phone, block_name, AOI) %>%
    summarise(fc=mean(!!sym(metri), na.rm=T), maas=mean(maas), tgjl=mean(tgjl), sas=mean(sas)) %>%
    filter(!is.na(fc)) %>%
    mutate(AOI=case_when(AOI == "b1_2_q"~"Q",
                         AOI == "b1_2_a"~"A",
                         AOI == "bg"~"BG")) %>%
    ungroup() %>%
    convert_as_factor(participant_phone, block_name, AOI) %>%
    select(participant_phone, block_name, AOI, tgjl, maas, sas, fc)
  
  
  # 极端值处理
  outdata <- dtc2 %>%
    group_by(AOI) %>%
    identify_outliers(fc)
  dtb3_r <- anti_join(dtc2, outdata)
  outdata2 <- dtb3_r %>%
    group_by(AOI) %>%
    identify_outliers(fc)
  dtb3_r2 <- anti_join(dtb3_r, outdata2)
  outdata3 <- dtb3_r2 %>%
    group_by(AOI) %>%
    identify_outliers(fc)
  dtb3_r3 <- anti_join(dtb3_r2, outdata3)
  outdata4 <- dtb3_r3 %>%
    group_by(AOI) %>%
    identify_outliers(fc)
  dtb3_r4 <- anti_join(dtb3_r3, outdata4)
  outdata5 <- dtb3_r4 %>%
    group_by(AOI) %>%
    identify_outliers(fc)
  
  
  # 模型拟合
  mixed_maas = lmer(fc ~ maas+AOI+maas*AOI+maas*block_name+AOI*block_name+AOI*block_name*maas + (1 | participant_phone), data = dtb3_r4)
  mixed_sas = lmer(fc ~ sas*AOI+sas*block_name+AOI*block_name+AOI*block_name*sas + (1 | participant_phone), data = dtb3_r4)
  mixed_two = lmer(fc ~ maas+sas+AOI+maas*sas+maas*AOI+sas*AOI+maas*block_name+AOI*block_name+sas*block_name+AOI*block_name*maas+AOI*block_name*sas+AOI*block_name*sas*maas + (1 | participant_phone), data = dtb3_r4)
  
  # maas 结果
  # 基本参数
  maas_t <- model_parameters(mixed_maas)
  maas_perfor <- model_performance(mixed_maas)
  maas_jh <- anova(mixed_maas)
  maas_eta <- eta_squared(mixed_maas)
  # 简单效应与配对检验
  maas_emm <- emmeans(mixed_maas, pairwise ~ AOI*block_name | maas, cov.reduce = function(x) quantile(x, c(0.1, 0.3, 0.5, 0.7,0.9)))
  maas_se1 <- joint_tests(mixed_maas , by=c("AOI"))
  maas_se1.5 <- joint_tests(mixed_maas , by=c("block_name"))
  maas_se2 <- joint_tests(mixed_maas , by=c("maas"), cov.reduce = function(x) quantile(x, c(0.1, 0.3, 0.5, 0.7,0.9)))
  
  # 交互作用可视化
  maas_inter_v <- emmip(mixed_maas, maas ~ AOI|block_name, mult.name = "variety", cov.reduce = FALSE)
  # 模型固定因子效应量
  maas_p1 <- plot_model(mixed_maas, show.values = TRUE, value.offset = .3, title = metri)
  # 模型交互1
  maas_p2 <- plot_model(mixed_maas, type = "pred", terms = c("maas", "AOI", "block_name"), title = metri, axis.title = metri)
  # 模型交互2
  maas_p3 <- plot_model(mixed_maas, type = "pred", terms = c("AOI", "maas", "block_name"), title = metri, axis.title = metri)
  # 结果汇总
  maas_results <- list(maas_t=maas_t, maas_perfor=maas_perfor, maas_jh=maas_jh, maas_eta=maas_eta,  maas_emm=maas_emm, maas_se1=maas_se1, maas_se2=maas_se2, maas_inter_v=maas_inter_v, p1=maas_p1, p2=maas_p2, maas_p3=maas_p3)
  
  # sas 结果
  # 基本参数
  sas_t <- model_parameters(mixed_sas)
  sas_perfor <- model_performance(mixed_sas)
  sas_jh <- anova(mixed_sas)
  sas_eta <- eta_squared(mixed_sas)
  # 简单效应与配对检验
  sas_emm <- emmeans(mixed_sas, pairwise ~ AOI*block_name | sas, cov.reduce = function(x) quantile(x, c(0.1, 0.3, 0.5, 0.7,0.9)))
  sas_se1 <- joint_tests(mixed_sas , by=c("AOI"))
  sas_se1.5 <- joint_tests(mixed_sas , by=c("block_name"))
  sas_se2 <- joint_tests(mixed_sas , by=c("sas"), cov.reduce = function(x) quantile(x, c(0.1, 0.3, 0.5, 0.7,0.9)))
  
  # 交互作用可视化
  sas_inter_v <- emmip(mixed_sas, sas ~ AOI|block_name, mult.name = "variety", cov.reduce = FALSE)
  # 模型固定因子效应量
  sas_p1 <- plot_model(mixed_sas, show.values = TRUE, value.offset = .3, title = metri)
  # 模型交互1
  sas_p2 <- plot_model(mixed_sas, type = "pred", terms = c("sas", "AOI", "block_name"), title = metri, axis.title = metri)
  # 模型交互2
  sas_p3 <- plot_model(mixed_sas, type = "pred", terms = c("AOI", "sas", "block_name"), title = metri, axis.title = metri)
  # 结果汇总
  sas_results <- list(sas_t=sas_t, sas_perfor=sas_perfor, sas_jh=sas_jh, sas_eta=sas_eta,  sas_emm=sas_emm, sas_se1=sas_se1, sas_se2=sas_se2, sas_inter_v=sas_inter_v, p1=sas_p1, p2=sas_p2, sas_p3=sas_p3)
  
  # two 结果
  two_t <- model_parameters(mixed_two)
  two_perfor <- model_performance(mixed_two)
  two_jh <- anova(mixed_two)
  two_eta <- eta_squared(mixed_two)
  # 简单效应与配对检验
  two_emm <- emmeans(mixed_two, pairwise ~ block_name|AOI | maas*sas, cov.reduce = function(x) quantile(x, c(0.3, 0.5, 0.7)))
  two_se1 <- joint_tests(mixed_two , by=c("AOI"))
  two_se2 <- joint_tests(mixed_two , by=c("maas"), cov.reduce = function(x) quantile(x, c(0.1, 0.3, 0.5, 0.7,0.9)))
  two_se3 <- joint_tests(mixed_two , by=c("sas"), cov.reduce = function(x) quantile(x, c(0.1, 0.3, 0.5, 0.7,0.9)))
  # 交互作用可视化
  two_inter_v_m <- emmip(mixed_two, maas ~ AOI|block_name, mult.name = "variety", cov.reduce = function(x) quantile(x, c(0.1,0.2, 0.3,0.4, 0.5,0.6, 0.7,0.8,0.9)))
  two_inter_v_s <- emmip(mixed_two, sas ~ AOI|block_name, mult.name = "variety", cov.reduce = function(x) quantile(x, c(0.1,0.2, 0.3,0.4, 0.5,0.6, 0.7,0.8,0.9)))
  two_inter_v <- emmip(mixed_two, maas ~ AOI|block_name|sas, mult.name = "variety", cov.reduce = function(x) quantile(x, c(0.1, 0.3, 0.5, 0.7,0.9)))
  # 模型固定因子
  two_p1 <- plot_model(mixed_two, show.values = TRUE, value.offset = .3, title = metri)
  # 模型交互1
  two_p2 <- plot_model(mixed_two, type = "pred", terms = c("maas", "sas", "AOI","block_name"), title = metri, axis.title = metri)
  # 模型交互2
  two_p3 <- plot_model(mixed_two, type = "pred", terms = c("sas", "maas", "AOI","block_name"), title = metri, axis.title = metri)
  
  two_results <- list(two_t=two_t, two_perfor=two_perfor, two_jh=two_jh, two_eta=two_eta,  two_emm=two_emm, two_se1=two_se1, two_se2=two_se2,  two_se3=two_se3, two_inter_v_m=two_inter_v_m,two_inter_v_s=two_inter_v_s, two_inter_v=two_inter_v, p1=two_p1, p2=two_p2, two_p3=two_p3)
  
  f <- list(maas_results, sas_results, two_results)

}

```

#### 参数定义
```{r, message=FALSE, warning=FALSE}
bname <- c("b1a", "b1b")
sname <- c(2,3,4,5)
a <- c("b1_2_q","b1_2_a", "bg")
mlist <- c("fc", "afd", "dff", "ffd", "pd", "dw", "asa", "sc", "sad", "asd", "spv")

```

## 分析
```{r, message=FALSE, warning=FALSE}
map(mlist,  possibly(mix_e_f, otherwise = NA_character_), dt=dt, bname=bname, sname=sname, a=a)
```
```