---
title: "b1_ana_5_1"
author: "Chen Xing"
date: '2022-05-07'
output:
  html_document: default
  word_document: default
  pdf_document: default
---

## 对b3进行 针对性分析 探索 type 与 量表 得分 与主观答题的关系, 中期汇报 版本


### 必要的包
```{r, message=FALSE, warning=FALSE, results='hide', echo=FALSE}
library(tidyverse)
library(rstatix)
library(ggpubr)
library(lmerTest)
library(sjPlot)
library(parameters)
library(effectsize)
library(emmeans)
library(performance)
```


### 开始分析

#### fangfa
```{r, message=FALSE, warning=FALSE}
mix_e_f <- function(dt, bname, sname, a, metri){
  # 数据准备
  dtc2 <- dt %>% filter(block_name %in% bname, stim %in% sname) %>%
    group_by(participant_phone, block_name, type,trial_name, stim) %>%
    summarise(fc=mean(!!sym(metri), na.rm=T), maas=mean(maas), tgjl=mean(tgjl), sas=mean(sas)) %>%
    filter(!is.na(fc)) %>%
    ungroup() %>%
    mutate(block_name=case_when(block_name=="b1a"~"Ex",
                                block_name=="b1b"~"In")) %>%
    convert_as_factor(participant_phone, block_name, type, trial_name,stim) %>%
    select(participant_phone,  block_name, type, trial_name, stim, tgjl, maas, sas, fc)
  
  
  # 极端值处理
  
  dtb3_r4 <- dtc2
  
  
  
  # 模型拟合
  mixed_maas = lmer(fc ~ maas+maas*type +  (1 | participant_phone)+(1 | trial_name), data = dtb3_r4)
  mixed_sas = lmer(fc ~ sas+sas*type +  (1 | participant_phone)+(1 | trial_name), data = dtb3_r4)
  
  # maas 结果
  # 基本参数
  maas_t <- model_parameters(mixed_maas)
  maas_perfor <- model_performance(mixed_maas)
  maas_jh <- anova(mixed_maas)
  maas_eta <- eta_squared(mixed_maas)
  # 简单效应与配对检验
  maas_emm <- emmeans(mixed_maas, pairwise ~ type | maas, cov.reduce = function(x) quantile(x, c(0.1, 0.3, 0.5, 0.7,0.9)))
  maas_emm2 <- emmeans(mixed_maas, pairwise ~ type)
  maas_se1.5 <- joint_tests(mixed_maas , by=c("type"))
  maas_se2 <- joint_tests(mixed_maas , by=c("maas"), cov.reduce = function(x) quantile(x, c(0.1, 0.3, 0.5, 0.7,0.9)))
  
  # 交互作用可视化
  maas_inter_v <- emmip(mixed_maas, maas ~ type, mult.name = "variety", cov.reduce = FALSE)
  # 模型固定因子效应量
  maas_p1 <- plot_model(mixed_maas, show.values = TRUE, value.offset = .3, title = metri)
  # 模型交互1
  maas_p2 <- plot_model(mixed_maas, type = "pred", terms = c("maas", "type"), title = metri, axis.title = metri)
  # 模型交互2
  maas_p3 <- plot_model(mixed_maas, type = "pred", terms = c("type","maas"), title = metri, axis.title = metri)
  # 结果汇总
  maas_results <- list(maas_t=maas_t, maas_perfor=maas_perfor, maas_jh=maas_jh, maas_eta=maas_eta,  maas_emm=maas_emm, maas_emm2=maas_emm2, maas_se2=maas_se2, maas_inter_v=maas_inter_v, p1=maas_p1, p2=maas_p2, maas_p3=maas_p3)
  
  # sas 结果
  # 基本参数
  sas_t <- model_parameters(mixed_sas)
  sas_perfor <- model_performance(mixed_sas)
  sas_jh <- anova(mixed_sas)
  sas_eta <- eta_squared(mixed_sas)
  # 简单效应与配对检验
  sas_emm <- emmeans(mixed_sas, pairwise ~ type | sas, cov.reduce = function(x) quantile(x, c(0.1, 0.3, 0.5, 0.7,0.9)))
  sas_emm2 <- emmeans(mixed_sas, pairwise ~ type)
  sas_se1.5 <- joint_tests(mixed_sas , by=c("type"))
  sas_se2 <- joint_tests(mixed_sas , by=c("sas"), cov.reduce = function(x) quantile(x, c(0.1, 0.3, 0.5, 0.7,0.9)))
  
  # 交互作用可视化
  sas_inter_v <- emmip(mixed_sas, sas ~ type, mult.name = "variety", cov.reduce = FALSE)
  # 模型固定因子效应量
  sas_p1 <- plot_model(mixed_sas, show.values = TRUE, value.offset = .3, title = metri)
  # 模型交互1
  sas_p2 <- plot_model(mixed_sas, type = "pred", terms = c("sas", "type"), title = metri, axis.title = metri)
  # 模型交互2
  sas_p3 <- plot_model(mixed_sas, type = "pred", terms = c("type","sas"), title = metri, axis.title = metri)
  # 结果汇总
  sas_results <- list(sas_t=sas_t, sas_perfor=sas_perfor, sas_jh=sas_jh, sas_eta=sas_eta,  sas_emm=sas_emm, sas_emm2=sas_emm2, sas_se2=sas_se2, sas_inter_v=sas_inter_v, p1=sas_p1, p2=sas_p2, sas_p3=sas_p3)
  

  
  f <- list(maas_results, sas_results)
}

```

#### 参数定义
```{r, message=FALSE, warning=FALSE}
bname <- c("b1a", "b1b")

a <- c("b1_2_a","b1_2_q", "bg")

mlist <- c("key")


dt <- read.csv("/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/ea/data/inner_dt_aoi_re_2.csv")

```

## 分析题目一 1虚构 2回忆
```{r, message=FALSE, warning=FALSE}
map(mlist,  possibly(mix_e_f, otherwise = NA_character_), dt=dt, bname=bname, sname=2, a=a)
```

## 分析题目二 1现实人物 2非现实人物
```{r, message=FALSE, warning=FALSE}
map(mlist,  possibly(mix_e_f, otherwise = NA_character_), dt=dt, bname=bname, sname=3, a=a)
```

## 分析题目三 人物数量
```{r, message=FALSE, warning=FALSE}
map(mlist,  possibly(mix_e_f, otherwise = NA_character_), dt=dt, bname=bname, sname=4, a=a)
```

## 分析题目三 情绪 1消极-5积极
```{r, message=FALSE, warning=FALSE}
map(mlist,  possibly(mix_e_f, otherwise = NA_character_), dt=dt, bname=bname, sname=5, a=a)
```