---
title: "GCA手动_2_tgjl_2"
author: "Chen Xing"
date: '2022-06-11'
output: html_document
---

## 摘要
手动gca_区分tgjl ，进一步优化分析

### 必要的包
```{r, message=FALSE, warning=FALSE, results='hide', echo=FALSE}
library(tidyverse)
library(lmerTest)
library(parameters)
library(effectsize)
library(emmeans)
library(performance)
library(sjPlot)
library(ggpubr)
library(rstatix)
```

### 读取数据
```{r, message=FALSE, warning=FALSE}
dt3_1 <- read_csv("/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/ea/data/b3_1_ot_tgjl.csv")
dt3_2 <- read_csv("/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/ea/data/b3_2_ot_tgjl.csv")
dt3_3 <- read_csv("/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/ea/data/b3_3_ot_tgjl.csv")
```


# 模型参数细节输出
```{r, message=FALSE, warning=FALSE}
dt3_1$Target <- factor(dt3_1$Target)

contrasts(dt3_1$Target) 

# 定义批量拟合方法
make.model2 <- function(dt, aoi){
  targetlevel <- c("high", "low")
  AOI_ne <- c("b3_ne", "b3_pos", "b3_neg", "b3_thr")
  AOI_pos <- c("b3_pos", "b3_ne", "b3_neg", "b3_thr")
  AOI_neg <- c("b3_neg", "b3_ne", "b3_pos", "b3_thr")
  AOI_thr <- c("b3_thr", "b3_ne", "b3_pos", "b3_neg")
  
  dt$Target <- factor(dt$Target, levels = targetlevel)
  
  if (aoi=="ne") {
    dt$AOI <- factor(dt$AOI, levels = AOI_ne)
    dt$AOISum <- C(dt$AOI, sum)
    info <- AOI_ne
  } else if (aoi=="pos"){
    dt$AOI <- factor(dt$AOI, levels = AOI_pos)
    dt$AOISum <- C(dt$AOI, sum)
    info <- AOI_pos
  } else if (aoi=="neg"){
    dt$AOI <- factor(dt$AOI, levels = AOI_neg)
    dt$AOISum <- C(dt$AOI, sum)
    info <- AOI_neg
  } else if (aoi=="thr"){
    dt$AOI <- factor(dt$AOI, levels = AOI_thr)
    dt$AOISum <- C(dt$AOI, sum)
    info <- AOI_thr
  }

  
  model.3 <- lmer(Elog ~ (ot1+ot2)*AOI*Target + (1| participant_phone), data = dt)
  model.4 <- lmer(Elog ~ (ot1+ot2+ot3)*AOI*Target + (1| participant_phone), data = dt)

  s.3 <- summary(model.3)
  
  s.4 <- summary(model.4)
  
  f <- list(targetlevel, info, s.3, s.4)
}

alist <- c("ne", "pos", "neg", "thr")

f3_1 <- map(alist, make.model2, dt=dt3_1)
f3_2 <- map(alist, make.model2, dt=dt3_2)
f3_3 <- map(alist, make.model2, dt=dt3_3)

print("Time 1")
f3_1

print("Time 2")
f3_2

print("Time 3")
f3_3
```


