---
title: "GCA手动_2_tgjl_ps_2"
author: "Chen Xing"
date: '2022-06-11'
output: html_document
---

## 摘要
手动gca_区分tgjl ，进一步优化分析ps

### 必要的包
```{r, message=FALSE, warning=FALSE, results='hide', echo=FALSE}
library(tidyverse)
library(lmerTest)
library(parameters)
library(effectsize)
library(emmeans)
library(performance)
library(sjPlot)
library(ggpubr)
library(rstatix)
```

### 读取数据
```{r, message=FALSE, warning=FALSE}
dt3_1 <- read_csv("/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/ea/data/b3_1_ot_ps_tgjl.csv")
dt3_2 <- read_csv("/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/ea/data/b3_2_ot_ps_tgjl.csv")
dt3_3 <- read_csv("/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/ea/data/b3_3_ot_ps_tgjl.csv")
```


# 模型参数细节输出
```{r, message=FALSE, warning=FALSE}


# 定义批量拟合方法
make.model2 <- function(dt){
  
  dt$Target <- factor(dt$Target)

  contrasts(dt$Target) 
  targetlevel <- c("HTA", "LTA")
  
  dt$Target <- factor(dt$Target, levels = targetlevel)
  

  
  
  model.4 <- lmer(ps ~ (ot1+ot2+ot3)*Target + (1| participant_phone) + (1|trial_id), data = dt)
  
  #model.5 <- lmer(ps ~ (ot1+ot2+ot3+ot4)*Target + (ot1+ot2+ot3+ot4| participant_phone), data = dt)

  #s.5 <- summary(model.5)
  
  s.4 <- summary(model.4)
  
  f <- list(targetlevel, s.4)
}



f3_1 <- make.model2(dt3_1)


print("Time 1")
f3_1


```


