---
title: "GCA_tgjl_gca_ps_1"
author: "Chen Xing"
date: '2022-06-10'
output: html_document
---

## 摘要
手动gca_区分tgjl  ps

### 必要的包
```{r, message=FALSE, warning=FALSE, results='hide', echo=FALSE}
library(tidyverse)
library(lmerTest)
library(parameters)
library(effectsize)
library(emmeans)
library(performance)
library(sjPlot)
library(ggpubr)
library(rstatix)
```

### 读取数据
```{r, message=FALSE, warning=FALSE}
dt <- read_csv("/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/ea/data/raw_time_b3_sas_ps.gz") %>%
  mutate(Target=case_when(tgjl_g=="high"~"HTA",
                          tgjl_g=="low"~"LTA"),
         AOI=case_when(AOI=="b3_ne"~"neutral",
                       AOI=="b3_neg"~"dysphoric",
                       AOI=="b3_pos"~"positive",
                       AOI=="b3_thr"~"threat")) %>%
  filter(tgjl_g != "mid") %>% rename(Time=time_bin)

dt_0 <- read_csv("/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/ea/data/b3_st0_ps.csv")

dt <- dt %>% full_join(dt_0) %>% mutate(ps=2*sqrt(ps/pi), psz=2*sqrt(psz/pi), ps=(ps-psz)/psz)

dt_all <- dt



ggplot(dt, aes(x=Time, y=ps, color=Target)) +
  stat_summary(fun.y=mean, geom="point")



```


### 开始gca
```{r, message=FALSE, warning=FALSE}
dt3 <- dt_all %>% filter(Target!="mid")

dt3$AOI <- as.factor(dt3$AOI)
dt$Target <- factor(dt$Target, levels = c("LTA", "HTA"))


# 针对timezone对数据进行切割
dt3_1 <- dt3 %>% filter(between(Time,0,7900)) %>% mutate(Time2=Time)
dt3_2 <- dt3 %>% filter(between(Time,7900,17700)) %>% mutate(Time2=Time, Time=Time-7900)
dt3_3 <- dt3 %>% filter(between(Time,17700,30000)) %>% mutate(Time2=Time, Time=Time-17700)
dt3_a <- dt3 %>% mutate(Time2=Time)



time_code_m <- function(dt3){
  dt3 <- dt3 %>% group_by(Target, participant_phone,trial_id, Time) %>%
    summarise(ps=mean(ps, rm.na=T), Time=min(Time), Time2=min(Time2)) %>%
    ungroup()
  
  orthogonal_polynomials <- poly(sort(as.vector(unique(dt3$Time))), 5)
  
  ggplot(data.frame(orthogonal_polynomials), aes(x=X1, y=X1)) +
                 geom_point() +
                 geom_point(aes(y=X2), color='red') +  
                 geom_point(aes(y=X3), color='blue') +
                 geom_point(aes(y=X4), color='green') +
                 geom_point(aes(y=X5), color='purple')
  
  time_codes <- data.frame(
                          sort(as.vector(unique(dt3$Time))),
                          orthogonal_polynomials[, c(1:5)]
                        )
  colnames(time_codes) <- c('Time','ot1','ot2','ot3','ot4','ot5')
  
  dt3 <- full_join(dt3, time_codes)
}

# 分别生成5段区间
dt3_1 <- time_code_m(dt3_1)
write_csv(dt3_1, "/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/ea/data/b3_1_ot_ps_tgjl.csv")
dt3_2 <- time_code_m(dt3_2)
write_csv(dt3_2, "/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/ea/data/b3_2_ot_ps_tgjl.csv")
dt3_3 <- time_code_m(dt3_3)
write_csv(dt3_3, "/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/ea/data/b3_3_ot_ps_tgjl.csv")
dt3_a <- time_code_m(dt3_a)
write_csv(dt3_a, "/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/ea/data/b3_a_ot_ps_tgjl.csv")


```



# 分别对各个区间进行模型拟合并比较模型
```{r, message=FALSE, warning=FALSE}
# 定义批量拟合方法
make.model <- function(dt){
  dt$Target <- factor(dt$Target, levels = c("LTA", "HTA"))
  model.base <- lmer(ps ~ (ot1+ot2+ot3) + (1| participant_phone) + (1|trial_id), data = dt)
  model.0 <- lmer(ps ~ (ot1+ot2+ot3)+Target + (1| participant_phone) + (1|trial_id), data = dt)
  model.1 <- lmer(ps ~ ot1*Target + (1| participant_phone) + (1|trial_id), data = dt)
  model.2 <- lmer(ps ~ (ot1+ot2)*Target + (1| participant_phone) + (1|trial_id), data = dt)
  model.3 <- lmer(ps ~ (ot1+ot2+ot3)*Target + (1| participant_phone) + (1|trial_id), data = dt)
  model.4 <- lmer(ps ~ (ot1+ot2+ot3+ot4)*Target + (1| participant_phone) + (1|trial_id), data = dt)
  
  m.comparsion <- anova(model.base, model.0, model.1, model.2, model.3, model.4)
  
  p.base <- ggplot(dt, aes(x=Time2, y=ps, color=Target)) +
                       stat_summary(fun.data=mean_se, geom="pointrange",alpha=0.75, size=0.3) +
                       stat_summary(aes(y=predict(model.base,dt,re.form=NA)), fun.y=mean, geom="line") +
                       labs(title = "m.base")
  s.base <- summary(model.base)
  
  p.0 <- ggplot(dt, aes(x=Time2, y=ps, color=Target)) +
                       stat_summary(fun.data=mean_se, geom="pointrange",alpha=0.75, size=0.3) +
                       stat_summary(aes(y=predict(model.0,dt,re.form=NA)), fun.y=mean, geom="line") +
                       labs(title = "m.0")
  s.0 <- summary(model.0)
  
  p.1 <- ggplot(dt, aes(x=Time2, y=ps, color=Target)) +
                       stat_summary(fun.data=mean_se, geom="pointrange",alpha=0.75, size=0.3) +
                       stat_summary(aes(y=predict(model.1,dt,re.form=NA)), fun.y=mean, geom="line") +
                       labs(title = "m.1")
  s.1 <- summary(model.1)
  
  p.2 <- ggplot(dt, aes(x=Time2, y=ps, color=Target)) +
                       stat_summary(fun.data=mean_se, geom="pointrange",alpha=0.75, size=0.3) +
                       stat_summary(aes(y=predict(model.2,dt,re.form=NA)), fun.y=mean, geom="line") +
                       labs(title = "m.2")
  s.2 <- summary(model.2)
  
  p.3 <- ggplot(dt, aes(x=Time2, y=ps, color=Target)) +
                       stat_summary(fun.data=mean_se, geom="pointrange",alpha=0.75, size=0.3) +
                       stat_summary(aes(y=predict(model.3,dt,re.form=NA)), fun.y=mean, geom="line") +
                       labs(title = "m.3")
  s.3 <- summary(model.3)
  
  p.4 <- ggplot(dt, aes(x=Time2, y=ps, color=Target)) +
                       stat_summary(fun.data=mean_se, geom="pointrange",alpha=0.75, size=0.3) +
                       stat_summary(aes(y=predict(model.4,dt,re.form=NA)), fun.y=mean, geom="line") +
                       labs(title = "m.4")
  s.4 <- summary(model.4)
  
  f <- list(m.comparsion, p.base, s.base, p.0, s.0, p.1, s.1, p.2, s.2, p.3, s.3, p.4, s.4)
}

f3_1 <- make.model(dt3_1)






print("Time 1")
f3_1


model.4 <- lmer(ps ~ (ot1+ot2+ot3+ot4)*Target + (1| participant_phone) + (1|trial_id), data = dt3_1)
p.4 <- ggplot(dt3_1, aes(x=Time2/1000, y=ps, color=Target)) +
                       stat_summary(fun.data=mean_se, geom="pointrange",alpha=0.75, size=0.3) +
                       stat_summary(aes(y=predict(model.4,dt3_1,re.form=NA)), fun.y=mean, geom="line") +
                       theme(axis.title.y=element_blank(),
                             axis.title.x=element_text(face = "bold"),
                             axis.text.x=element_text(face = "bold"),
                             axis.text.y=element_text(face = "bold"),
                             strip.text.y=element_text(face = "bold"),
                             legend.text=element_text(face = "bold")) +
                       labs(colour = "Group") +
                       labs(y="Pupil diameter (percentage)") +
                       labs(x="Time(s)")
p5_npg = p.4 + ggsci::scale_color_nejm()
p5_npg


f3_2 <- make.model(dt3_2)
print("Time 2")
f3_2

f3_3 <- make.model(dt3_3)
print("Time 3")
f3_3

```
