---
title: "b3时序原始数据生成"
author: "Chen Xing"
date: '2022-06-08'
output: html_document
---

## 摘要
b3时序原始数据生成,基于tgjl

### 必要的包
```{r, message=FALSE, warning=FALSE, results='hide', echo=FALSE}
library(tidyverse)
library(data.table)
library(furrr)
library("Matrix")
library("lme4")
library("ggplot2")
library("eyetrackingR")
plan(multisession, workers = 6)
```



```{r, message=FALSE, warning=FALSE}
dt3_1 <- fread("/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/tidy/b3_raw.csv.gz") %>%
  mutate(participant_phone=as.numeric(participant_phone)) %>%
  select(1:15, b3_pos, b3_neg, b3_thr, b3_ne, trackloss)

msg <- read_csv("/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/tidy/scale_sum_r.csv") %>%
  select(participant_phone, tgjl_g)

dt_a <- full_join(dt3_1, msg) %>% drop_na(trial_id)

gc()

dt_l <- make_eyetrackingr_data(dt_a, 
                       participant_column = "participant_phone",
                       trial_column = "trial_id",
                       time_column = "time_p",
                       trackloss_column = "trackloss",
                       aoi_columns = c("b3_pos", "b3_neg", "b3_thr", "b3_ne"),
                       treat_non_aoi_looks_as_missing = TRUE
)

# subset to response window post word-onset
response_window <- subset_by_window(dt_l, 
                                    window_start_time = 1, 
                                    window_end_time = 30000, 
                                    rezero = FALSE)

trackloss <- trackloss_analysis(data = response_window)

# remove trials with > 25% of trackloss
response_window_clean <- clean_by_trackloss(data = response_window, trial_prop_thresh = .25)

# create Target condition column
response_window_clean$Target <- as.factor(response_window_clean$tgjl_g)

# aggregate across trials within subjects in time analysis
response_time <- make_time_sequence_data(response_window_clean, time_bin_size = 100, 
                                 predictor_columns = c("Target"),
                                 aois = c("b3_pos", "b3_neg", "b3_thr", "b3_ne")
                            )


# 保存时序数据
write_csv(response_time, "/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/ea/data/raw_time_b3_tgjl_1.gz")

# visualize time results
plot(response_time, predictor_column = "Target") + 
  theme_light() +
  coord_cartesian(ylim = c(0,1))
```
