---
title: "Time_bin_mixed_tgjls-pub"
author: "Chen Xing"
date: '2022-06-10'
output: html_document
---

## 摘要
针对瞳孔直径出时序图并进行mixed模型差异分析, 按照tgjl进行分组，进一步优化分析

### 必要的包
```{r, message=FALSE, warning=FALSE, results='hide', echo=FALSE}
library(tidyverse)
library(lmerTest)
library(emmeans)
library("ggplot2")
library("gridExtra")
library(viridis)
library(ggthemes)
library(cowplot)
library(ggpubr)
```

### 读取数据初步时序图
```{r, message=FALSE, warning=FALSE}
dt <- read_csv("/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/ea/data/raw_time_b3_sas_ps.gz") %>%
  mutate(Target=case_when(tgjl_g=="high"~"HTA",
                          tgjl_g=="low"~"LTA"),
         AOI=case_when(AOI=="b3_ne"~"neutral",
                       AOI=="b3_neg"~"dysphoric",
                       AOI=="b3_pos"~"positive",
                       AOI=="b3_thr"~"threat")) %>%
  filter(tgjl_g != "mid") %>% rename(Time=time_bin)

dt_all <- dt
dt_pos <- dt %>% filter(AOI == "positive")


ggplot(dt, aes(x=Time, y=ps, color=Target)) +
  stat_summary(fun.y=mean, geom="point")

ggplot(dt_pos, aes(x=Time, y=ps, color=Target)) +
  stat_summary(fun.y=mean, geom="point")
```





### 进行时序区间划分
```{r, message=FALSE, warning=FALSE}

nt <- c(7.9,18.0)

```


### 进行叠加可视化
```{r, message=FALSE, warning=FALSE}
dt_v2 <- dt_all %>% mutate(Time=Time/1000, AOI=factor(AOI, levels=c("threat",  "dysphoric", "positive", "neutral")))


dt_v3 <- dt_pos %>% mutate(Time=Time/1000, AOI=factor(AOI, levels=c("threat",  "dysphoric", "positive", "neutral")))





p4 <- ggplot(dt_v2, aes(x=Time, y=ps, color=Target)) +
  #facet_grid(rows = vars(Target)) +
  stat_summary(fun.y=mean, geom="line", size=1, alpha = 0.75) +
  geom_vline(xintercept = nt,linetype="dotted", 
                color = "black", size=1, alpha = 0.55) +
  theme(legend.key.size = unit(5, "pt"), legend.position = "right", legend.key.width = unit(15, "pt"), legend.title=element_text(face = "bold"), axis.title.x=element_text(face = "bold"),
        axis.title.y=element_text(face = "bold"),
        axis.text.x=element_text(face = "bold"),
        axis.text.y=element_text(face = "bold"),
        strip.text.y=element_text(face = "bold"),
        legend.text=element_text(face = "bold"),
        plot.margin=unit(c(0,1,1,1), "cm")) +
  labs(colour = "Stimuli") +
  labs(y="Gaze proportion") +
  labs(x="Time(s)")+
  scale_x_continuous(breaks = append(nt, c(0,30)))

p5 <- ggplot(dt_v3, aes(x=Time, y=ps, color=Target)) +
  #facet_grid(rows = vars(Target)) +
  stat_summary(fun.y=mean, geom="line", size=1, alpha = 0.75) +
  geom_vline(xintercept = nt,linetype="dotted", 
                color = "black", size=1, alpha = 0.55) +
  theme(legend.key.size = unit(5, "pt"), legend.position = "right", legend.key.width = unit(15, "pt"), legend.title=element_text(face = "bold"), axis.title.x=element_text(face = "bold"),
        axis.title.y=element_text(face = "bold"),
        axis.text.x=element_text(face = "bold"),
        axis.text.y=element_text(face = "bold"),
        strip.text.y=element_text(face = "bold"),
        legend.text=element_text(face = "bold"),
        plot.margin=unit(c(0,1,1,1), "cm")) +
  labs(colour = "Stimuli") +
  labs(y="Gaze proportion") +
  labs(x="Time(s)")+
  scale_x_continuous(breaks = append(nt, c(0,30)))

p4_npg = p4 + ggsci::scale_color_npg()
p5_npg = p5 + ggsci::scale_color_npg()

#fig2 <- plot_grid(p3, p4_npg, ncol = 1, align = "v",rel_heights = c(1, 2), labels = c("A", "B"))

#fig2
p4_npg
p5_npg

#ggsave(filename = "/Users/placenameday/Downloads/fig2.pdf", width = 180, height = 120, units = "mm")
```


