---
title: "b2_ana_1"
author: "Chen Xing"
date: '2022-05-06'
output:
  html_document: default
  word_document: default
  pdf_document: default
---

## 对b2进行 数据准备


### 必要的包
```{r, message=FALSE, warning=FALSE, results='hide', echo=FALSE}
library(tidyverse)
library(furrr)
```


### b2 数据处理
```{r, message=FALSE, warning=FALSE}
# 数据导入
dt <- read_csv("/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/tidy/b2_raw_clean_aoi/1022_raw.zip.gz.gz")

b2_p <- function(dt){
  dt <- read_csv(dt) %>%
    mutate(participant_phone=as.numeric(participant_phone), block=as.numeric(block), stim=as.numeric(stim), gaze=as.numeric(gaze), pd=as.numeric(pd))
}


b2_mer <- function(in_dir, out_dir){
  in_list <- paste(in_dir,"/",list.files(in_dir), sep = "")

  write_excel_csv(bind_rows(future_map(in_list, b2_p)), out_dir)
}
indir <- "/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/tidy/b2_raw_clean_aoi"
out_d <- "/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/ea/data/b2_raw.csv"

```
运行`b2_mer(indir, out_d)`


### b2 数据整合acc与rt
```{r, message=FALSE, warning=FALSE}
b2dt <- read_csv("/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/ea/data/b2_raw.csv")

msg <- read_csv("/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/tidy/msg_r.csv") %>%
  select(participant_phone, block, block_name, acc, rt, type, ans) %>%
  filter(block_name=="b2", rt>=0) %>%
  mutate(star1=str_split_fixed(type, "-", 2)) %>%
  mutate(ansP=if_else(ans=="f", star1[,1],star1[,2])) %>%
  select(participant_phone, block, block_name, acc, rt, type, ansP) %>%
  mutate(R=if_else(acc==1,1,0),W=if_else(acc==2,1,0)) %>%
  group_by(participant_phone, block_name, ansP) %>%
  summarise(R=sum(R), W=sum(W), rt=mean(rt)) %>%
  mutate(acc=R/(R+W)) %>% select(-R,-W)

msg2 <- read_csv("/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/tidy/msg_r.csv") %>%
  select(participant_phone, block, block_name, acc, rt, type, ans) %>%
  filter(block_name=="b2", rt>=0) %>%
  mutate(star1=str_split_fixed(type, "-", 2)) %>%
  mutate(ansP=if_else(ans=="f", star1[,1],star1[,2])) %>%
  select(participant_phone, block, block_name, type, ansP)

scale <- read_csv("/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/tidy/scale_sum_r.csv") %>%
  select(participant_phone,maas,sas,tgjl)

b2ad <- full_join(b2dt,msg2)
b2ad2 <- full_join(b2ad, msg)
b2ad2 <- full_join(b2ad2, scale)

write_excel_csv(b2ad2, "/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/ea/data/b2_info.csv")

```
