---
title: "Static_ana_4"
author: "Chen Xing"
date: '2022-05-02'
output: html_document
---

## 对b3进行 量表得分 x aoi 混合重复测量方差分析


### 必要的包
```{r, message=FALSE, warning=FALSE, results='hide', echo=FALSE}
library(tidyverse)
library(rstatix)
library(ggpubr)
```

### 开始分析
#### 数据准备
```{r, message=FALSE, warning=FALSE}
# 数据导入
dt <- read.csv("/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/ea/data/inner_dt_aoi_re.csv")
```

#### 方法定义 参数检验
```{r, message=FALSE, warning=FALSE}
mixa <- function(dt, bname, sname, a, group, metri){
  
  dtb3 <- dt %>% filter(block_name==bname, stim==sname, AOI %in% a) %>%
    mutate(tgroup=!!sym(group)) %>%
    filter(tgroup!="mid") %>%
    group_by(participant_phone, tgroup, AOI) %>%
    summarise(fc=mean(!!sym(metri), rm.na=T)) %>%
    select(participant_phone, tgroup, fc, AOI) %>%
    convert_as_factor(participant_phone, tgroup, AOI) %>% ungroup()
  
  outdata <- dtb3 %>%
    group_by(AOI, tgroup) %>%
    identify_outliers(fc)
  dtb3_r <- anti_join(dtb3, outdata)
  outdata2 <- dtb3_r %>%
    group_by(AOI, tgroup) %>%
    identify_outliers(fc)
  dtb3_r2 <- anti_join(dtb3_r, outdata2)
  outdata3 <- dtb3_r2 %>%
    group_by(AOI, tgroup) %>%
    identify_outliers(fc)
  dtb3_r3 <- anti_join(dtb3_r2, outdata3)
  outdata4 <- dtb3_r3 %>%
    group_by(AOI, tgroup) %>%
    identify_outliers(fc)
  dtb3_r4 <- anti_join(dtb3_r3, outdata4)
  outdata5 <- dtb3_r4 %>%
    group_by(AOI, tgroup) %>%
    identify_outliers(fc)
  
  ms <- dtb3_r4 %>%
    group_by(AOI, tgroup) %>%
    get_summary_stats(fc, type = "mean_sd")
  
  bxp <- ggboxplot(
    dtb3_r4, x = "AOI", y = "fc",
    color = "tgroup", palette = "jco"
  ) + labs(y=metri)
  bxp
  
  ztx <- dtb3_r4 %>%
    group_by(AOI, tgroup) %>%
    shapiro_test(fc)
  
  ztp <- ggqqplot(dtb3_r4, "fc", ggtheme = theme_bw()) +
    facet_grid(AOI ~ tgroup)
  
  qx <- dtb3_r4 %>%
    group_by(AOI) %>%
    levene_test(fc ~ tgroup)
  
  res.aov <- anova_test(
    data = dtb3_r4, dv = fc, wid = participant_phone,
    between = tgroup, within = AOI
  )
  fc <- get_anova_table(res.aov)
  
  # Effect of group at each time point
  one.way <- dtb3_r4 %>%
    group_by(AOI) %>%
    anova_test(dv = fc, wid = participant_phone, between = tgroup) %>%
    get_anova_table() %>%
    adjust_pvalue(method = "bonferroni")
  one.way
  
  # Pairwise comparisons between group levels
  pwc <- dtb3_r4 %>%
    group_by(AOI) %>%
    pairwise_t_test(fc ~ tgroup, p.adjust.method = "bonferroni")
  sh <- pwc
  
  # Effect of time at each level of exercises group
  one.way2 <- dtb3_r4 %>%
    group_by(tgroup) %>%
    anova_test(dv = fc, wid = participant_phone, within = AOI) %>%
    get_anova_table() %>%
    adjust_pvalue(method = "bonferroni")
  one.way2
  
  # Pairwise comparisons between time points at each group levels
  # Paired t-test is used because we have repeated measures by time
  pwc2 <- dtb3_r4 %>%
    group_by(tgroup) %>%
    pairwise_t_test(
      fc ~ AOI, paired = F, 
      p.adjust.method = "bonferroni"
    )
  pwc2
  
  
  # Visualization: boxplots with p-values
  pwc <- pwc %>% add_xy_position(x = "AOI")
  pwc.filtered <- pwc
  f <- bxp + 
    stat_pvalue_manual(pwc.filtered, tip.length = 0, hide.ns = TRUE) +
    labs(
      subtitle = get_test_label(res.aov, detailed = TRUE),
      caption = get_pwc_label(pwc)
    )
  list(ztx=ztx, ztp=ztp, ms=ms, qx=qx, fc=fc, jd1=one.way, jd2=one.way2, sh=sh, sh2=pwc2, f=f)
}

```

#### 方法定义 非参数检验kw
```{r, message=FALSE, warning=FALSE}
mixa_f <- function(dt, bname, sname, a, group, metri){
  dtb3 <- dt %>% filter(block_name==bname, stim==sname, AOI %in% a) %>%
    mutate(tgroup=!!sym(group)) %>%
    filter(tgroup!="mid") %>%
    group_by(participant_phone, tgroup) %>%
    summarise(fc=mean(!!sym(metri), rm.na=T)) %>%
    select(participant_phone, tgroup, fc) %>%
    convert_as_factor(participant_phone, tgroup) %>% ungroup()
  
  ms <- dtb3 %>% 
    group_by(tgroup) %>%
    get_summary_stats(fc, type = "common")
  
  res.kruskal <- dtb3 %>% kruskal_test(fc ~ tgroup)
  res.kruskal
  
  effsize <- dtb3 %>% kruskal_effsize(fc ~ tgroup)
  
  pwc <- dtb3 %>% 
    dunn_test(fc ~ tgroup, p.adjust.method = "bonferroni") 
  db <- pwc
  
  pwc <- pwc %>% add_xy_position(x = "troup")
  f <- ggboxplot(dtb3, x = "tgroup", y = "fc") +
    stat_pvalue_manual(pwc, hide.ns = TRUE) +
    labs(
      subtitle = get_test_label(res.kruskal, detailed = TRUE),
      caption = get_pwc_label(pwc),
      y=metri
      )
  list(ms, res.kruskal, effsize, db, f)
}
```

#### 方法定义 非参数检验friedman
```{r, message=FALSE, warning=FALSE}
mixa_f2 <- function(dt, bname, sname, a, group, gd, metri){
  dtb3 <- dt %>% filter(block_name==bname, stim==sname, AOI %in% a) %>%
    mutate(tgroup=!!sym(group)) %>%
    filter(tgroup==gd) %>%
    group_by(participant_phone, AOI) %>%
    summarise(fc=mean(!!sym(metri), rm.na=T)) %>%
    select(participant_phone, AOI, fc) %>%
    pivot_wider(names_from = AOI, values_from = fc) %>%
    mutate_if(is.numeric, ~replace(., is.na(.), 0)) %>%
    pivot_longer(2:5, names_to = "AOI", values_to = "fc") %>%
    ungroup() %>%
    arrange(AOI, participant_phone) %>%
    convert_as_factor(participant_phone, AOI)
  
  ms <- dtb3 %>% 
    group_by(AOI) %>%
    get_summary_stats(fc, type = "common")
  
  res.fried <- dtb3 %>% friedman_test(fc ~ AOI |participant_phone)
  res.fried
  
  effsize <- dtb3 %>% friedman_effsize(fc ~ AOI |participant_phone)
  
  # pairwise comparisons
  pwc <- dtb3 %>%
    wilcox_test(fc ~ AOI, paired = TRUE, p.adjust.method = "bonferroni")
  db <- pwc
  
  # Visualization: box plots with p-values
  pwc <- pwc %>% add_xy_position(x = "AOI")
  f <- ggboxplot(dtb3, x = "AOI", y = "fc", add = "point") +
    stat_pvalue_manual(pwc, hide.ns = TRUE) +
    labs(
      subtitle = get_test_label(res.fried,  detailed = TRUE),
      caption = get_pwc_label(pwc),
      y=metri
    )
  list(ms, res.fried, effsize, db, f)
}
```


#### 参数定义
```{r, message=FALSE, warning=FALSE}
block <- "b3"
stim <- 1
aoilist <- c("b3_ne","b3_pos", "b3_neg", "b3_thr")
aoilist2 <- c("outter_l","outter_r", "outter_t", "outter_b")
glist <- c("tgjl_g", "maas_g", "sas_g")
mlist <- c("fc", "afd", "dff", "ffd", "pd", "dw", "asa", "sc", "sad", "asd", "spv")
mlist2 <- c("fc", "dff", "dw", "asa")
```

## tgjl上的混合效应
```{r, message=FALSE, warning=FALSE}
map(mlist, mixa, dt=dt, bname=block, sname=stim, a=aoilist, group="tgjl_g")
```

## maas上的混合效应
```{r, message=FALSE, warning=FALSE}
map(mlist, mixa, dt=dt, bname=block, sname=stim, a=aoilist, group="maas_g")
```

## sas上的混合效应
```{r, message=FALSE, warning=FALSE}
map(mlist, mixa, dt=dt, bname=block, sname=stim, a=aoilist, group="sas_g")
```

## tgjl在屏幕外的混合效应
```{r, message=FALSE, warning=FALSE}
map(mlist, mixa_f, dt=dt, bname=block, sname=stim, a=aoilist2, group="tgjl_g")
```

## tgjl高的在屏幕外的混合效应
```{r, message=FALSE, warning=FALSE}
map(mlist2, mixa_f2, dt=dt, bname=block, sname=stim, a=aoilist2, group="tgjl_g", gd="high")
```

## tgjl低的在屏幕外的混合效应
```{r, message=FALSE, warning=FALSE}
map(mlist2, mixa_f2, dt=dt, bname=block, sname=stim, a=aoilist2, group="tgjl_g", gd="low")
```

## maas在屏幕外的混合效应
```{r, message=FALSE, warning=FALSE}
map(mlist, mixa_f, dt=dt, bname=block, sname=stim, a=aoilist2, group="maas_g")
```

## maas高的在屏幕外的混合效应
```{r, message=FALSE, warning=FALSE}
map(mlist2, mixa_f2, dt=dt, bname=block, sname=stim, a=aoilist2, group="maas_g", gd="high")
```

## maas低的在屏幕外的混合效应
```{r, message=FALSE, warning=FALSE}
map(mlist2, mixa_f2, dt=dt, bname=block, sname=stim, a=aoilist2, group="maas_g", gd="low")
```

## sas在屏幕外的混合效应
```{r, message=FALSE, warning=FALSE}
map(mlist, mixa_f, dt=dt, bname=block, sname=stim, a=aoilist2, group="sas_g")
```

## sas高的在屏幕外的混合效应
```{r, message=FALSE, warning=FALSE}
map(mlist2, mixa_f2, dt=dt, bname=block, sname=stim, a=aoilist2, group="sas_g", gd="high")
```

## sas低的在屏幕外的混合效应
```{r, message=FALSE, warning=FALSE}
map(mlist2, mixa_f2, dt=dt, bname=block, sname=stim, a=aoilist2, group="sas_g", gd="low")
```
