---
title: "b3_ana_1"
author: "Chen Xing"
date: '2022-05-01'
output: html_document
---

## 对b3进行整体aoi重复测量方差分析


### 必要的包
```{r, message=FALSE, warning=FALSE, results='hide', echo=FALSE}
library(tidyverse)
library(rstatix)
library(ggpubr)
```


### 对block3进行分析
#### block3各个情绪AOI的总体对比方法定义
```{r, message=FALSE, warning=FALSE}
# 数据导入
dt <- read.csv("/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/ea/data/inner_dt_aoi_re.csv")

ma <- function(dt, bname, st, aoi, metri){
  # 数据筛选
  dtb3 <- dt %>% filter(block_name==bname, stim==st, AOI %in% aoi) %>%
    group_by(participant_phone, AOI) %>% select(participant_phone, metri, AOI) %>%
    summarise(fc=mean(!!sym(metri), rm.na=T)) %>%
    convert_as_factor(participant_phone, AOI) %>% ungroup()
  
  outdata <- dtb3 %>%
    group_by(AOI) %>%
    identify_outliers(fc)
  
  dtb3_r <- anti_join(dtb3, outdata)
  
  outdata2 <- dtb3_r %>%
    group_by(AOI) %>%
    identify_outliers(fc)
  
  dtb3_r2 <- anti_join(dtb3_r, outdata2)
  
  outdata3 <- dtb3_r2 %>%
    group_by(AOI) %>%
    identify_outliers(fc)
  
  dtb3_r3 <- anti_join(dtb3_r2, outdata3)
  
  outdata4 <- dtb3_r3 %>%
    group_by(AOI) %>%
    identify_outliers(fc)
  
  ztx <- dtb3_r3 %>%
    group_by(AOI) %>%
    shapiro_test(fc)
  
  ztx_pic <- ggqqplot(dtb3_r3, "fc", facet.by = "AOI")
  
  miaoshu <- dtb3_r3 %>%
    group_by(AOI) %>%
    get_summary_stats(fc, type = "mean_sd")
  
  bxp <- ggboxplot(dtb3_r3, x = "AOI", y = "fc") + labs(y=metri)
  bxp
  
  res.aov <- anova_test(data = dtb3_r3, dv = fc, wid = participant_phone, within = AOI)
  fangcha <- get_anova_table(res.aov)
  
  
  pwc <- dtb3_r3 %>%
    pairwise_t_test(
      fc ~ AOI, paired = F,
      p.adjust.method = "bonferroni"
    )
  sh <- pwc
  
  pwc <- pwc %>% add_xy_position(x = "AOI")
  f <- bxp + 
    stat_pvalue_manual(pwc, hide.ns = TRUE) +
    labs(
      subtitle = get_test_label(res.aov, detailed = TRUE),
      caption = get_pwc_label(pwc)
    )
  list(ztx=ztx, ztxp=ztx_pic, ms=miaoshu, fc=fangcha, sh=sh, f=f)
}
```


#### 参数定义
```{r, message=FALSE, warning=FALSE}
block <- "b3"
stim <- 1
aoilist <- c("b3_ne","b3_pos", "b3_neg", "b3_thr")
aoilist2 <- c("outter_l","outter_r", "outter_t", "outter_b")
mlist <- c("fc", "afd", "dff", "ffd", "pd", "dw", "asa", "sc", "sad", "asd", "spv")
```


## 情绪aoi上的主效应
```{r, message=FALSE, warning=FALSE}
map(mlist, ma, dt=dt, bname=block, st=stim, aoi=aoilist)

```


## 屏幕外aoi上的主效应
```{r, message=FALSE, warning=FALSE}
map(mlist,  possibly(ma, otherwise = NA_character_), dt=dt, bname=block, st=stim, aoi=aoilist2)
```

