---
title: "scale2"
author: "Chen Xing"
date: '2022-05-13'
output: html_document
---

```{r, message=FALSE, warning=FALSE, results='hide', echo=FALSE}
library(tidyverse)
library(psych)
library(readxl)
library(table1)
```


# 统计问卷基本信息
```{r, message=FALSE, warning=FALSE}
# 数据读取
dt <- read_csv("/Users/placenameday/R study/edf_demo/data/processed/sclae_cred/processed/all_4.csv")

dt2 <- dt %>% select(participant_phone, sex, age, edu, tzjl, maas, phoneadd) %>%
  mutate(age=case_when(age=="26-30" ~ 28,
                       age=="18-22" ~ 20,
                       age=="22-26" ~ 24), sex=case_when(sex=="男" ~ "male",
                                                         sex=="女" ~ "female"))

# 平均年龄
mean(dt2$age)

# 描述统计
f <- dt2 %>% group_by(sex) %>%
  summarise(N=n(), maas=mean(maas, na.rm=T), sas=mean(phoneadd, na.rm=T), tzjl=mean(tzjl, na.rm=T))
f

f2 <- dt2 %>%
  summarise(maas=mean(maas, na.rm=T), sas=mean(phoneadd, na.rm=T), tzjl=mean(tzjl, na.rm=T))

f3 <- dt2 %>%
  summarise(maas=sd(maas, na.rm=T), sas=sd(phoneadd, na.rm=T), tzjl=sd(tzjl, na.rm=T))

```
