---
title: "data_cleanning_aoi_2"
author: "Chen Xing"
date: '2022-04-19'
output: html_document
---

# 根据具体刺激生成的AOI区域对数据进行aoi打标 2

用R进行大量运算速度较慢，建议改用python进行

## 必要的包

```{r, message=FALSE, warning=FALSE, results='hide'}
library(tidyverse)
library(data.table)
library(furrr)
library(progress)
plan(multisession, workers = 4)
```

## 整合所有aoi信息

```{r, message=FALSE, warning=FALSE}
aoi_dir <- "/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/tidy/AOI_info_3/"
aoi_list <- list.files(aoi_dir)

# 定义aoi文件信息整理方法
std_aoi <- function(file){
  aoi_name <- str_split_fixed(file, "\\.",2)[1]
  aoi_info <- read_csv(paste(aoi_dir, file, sep = "")) %>%
    filter(!is.null(Left)) %>%
    mutate(aoi_name=aoi_name) %>%
    select(block_name, stim_name, stim, aoi_name, Left, Top, Right, Bottom) %>%
    rename(trial_name=stim_name) %>%
    arrange(block_name, trial_name, aoi_name)
}

# 整合aoi文件
aoi_info <- reduce(map(aoi_list, std_aoi),full_join) %>% filter(!is.na(Left))
write_excel_csv(aoi_info, "/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/tidy/AOI_info_3.csv")

```

## 定义打标方法

```{r, message=FALSE, warning=FALSE}


# 定义判断是否落入AOI方法
# raw 文件判断
aj_r <- function(n, l, t, r, b, dt) {
    dt[[n]] <- with(dt, if_else((l<=xp&xp<=r)&(t<=yp&yp<=b),TRUE,FALSE))
    dt
}

# fix 文件判断
aj_f <- function(n, l, t, r, b, dt) {
    dt[[n]] <- with(dt, if_else((l<=axp&axp<=r)&(t<=ayp&ayp<=b),TRUE,FALSE))
    dt
}

# saac_多种情况 文件判断
aj_s <- function(n, l, t, r, b, dt) {
    dt[[n]] <- with(dt, if_else(((l<=sxp&sxp<=r)&(t<=syp&syp<=b))&((l<=exp&exp<=r)&(t<=eyp&eyp<=b)),"Inner",
                        if_else((l<=sxp&sxp<=r)&(t<=syp&syp<=b), "S",
                        if_else((l<=exp&exp<=r)&(t<=eyp&eyp<=b),"E","None"))))
    dt
}

# 定义单个stimAOI判断与汇总方法
trial_stim_aoi <- function(stim_n, ai2 = aoi_info, f2 = file, m2){
  aoi_stim_info <- filter(ai2, stim==stim_n)
  stim_file <- filter(f2, stim==stim_n)
  suppressMessages(reduce(future_pmap(list(aoi_stim_info$aoi_name, aoi_stim_info$Left, aoi_stim_info$Top, aoi_stim_info$Right, aoi_stim_info$Bottom), m2, dt=stim_file),suppressMessages(full_join)))
}


# 定义单个trialAOI判断与汇总方法
trial_name_aoi <- function(trial_n, ai = aoi_info, f = file, m){
  aoi_trial_info <- filter(ai, trial_name==trial_n)
  trial_file <- filter(f, trial_name==trial_n)
  stim_list <- unique(trial_file$stim)
  suppressMessages(reduce(future_map(stim_list, trial_stim_aoi, ai2=aoi_trial_info, f2=trial_file, m2=m),suppressMessages(full_join)))
}

bg_de <- function(l){
  v <- ifelse(sum(l %in% c("None"))==length(l), "Inner",
        ifelse(sum(l %in% c("None", "S"))==length(l), "E",
          ifelse(sum(l %in% c("None", "E"))==length(l), "S", "None")))
  v
}


bg_de2 <- function(l){
  v <- ifelse(sum(l %in% c(FALSE))==length(l), TRUE, FALSE)
  v
}

# 定义背景AOI判断方法
sub_bg_aoi <- function(dt){
  if ("sxp" %in% colnames(dt)) {
    
    ndt1 <- dt %>% filter(block_name %in% c("b1a", "b1b") & stim %in% c(2,3,4,5))
    if (nrow(ndt1)==0) {
      ndt1
    } else {
      ndt1 <- ndt1 %>% rowwise() %>%
        mutate(bg=bg_de(c(b1_2_q,b1_2_a)))
    }
    
    ndt2 <- dt %>% filter(block_name %in% c("b2"))
    if (nrow(ndt2)==0) {
      ndt2
    } else {
      ndt2 <- ndt2 %>% rowwise() %>%
        mutate(bg=bg_de(c(b2_left,b2_center,b2_right)))
    }
   
    ndt3 <- dt %>% filter(block_name %in% c("b4a", "b4b"))
    if (nrow(ndt3)==0) {
      ndt3
    } else {
      ndt3 <- ndt3 %>% rowwise() %>%
        mutate(bg=bg_de(c(b4_text)))
    }
    
    ndt4 <- dt %>% filter(block_name %in% c("b5a"))
    if (nrow(ndt4)==0) {
      ndt4
    } else {
      ndt4 <- ndt4 %>% rowwise() %>%
        mutate(bg=bg_de(c(b5_q,b5_a_1,b5_a_2,b5_a_3,b5_a_4)))
    }
    
    ndt5 <- dt %>% filter(block_name %in% c("b5b"))
    if (nrow(ndt4)==0) {
      ndt5
    } else {
      ndt5 <- ndt5 %>% rowwise() %>%
        mutate(bg=bg_de(c(b5_q,b5_a_1,b5_a_2,b5_a_3,b5_a_4,b5_a_5,b5_a_6)))
    }
  } else  {
      if ("xp" %in% colnames(dt)) {
        dt2 <- filter(dt, !is.na(xp))
      } else dt2 <- dt
      ndt1 <- dt2 %>% filter(block_name %in% c("b1a", "b1b") & stim %in% c(2,3,4,5))
      if (nrow(ndt1)==0) {
        ndt1
      } else {
        ndt1 <- ndt1 %>% rowwise() %>%
          mutate(bg=bg_de2(c(b1_2_q,b1_2_a)))
      }
      
      ndt2 <- dt2 %>% filter(block_name %in% c("b2"))
      if (nrow(ndt2)==0) {
        ndt2
      } else {
        ndt2 <- ndt2 %>% rowwise() %>%
          mutate(bg=bg_de2(c(b2_left,b2_center,b2_right)))
      }
     
      ndt3 <- dt2 %>% filter(block_name %in% c("b4a", "b4b"))
      if (nrow(ndt3)==0) {
        ndt3
      } else {
        ndt3 <- ndt3 %>% rowwise() %>%
          mutate(bg=bg_de2(c(b4_text)))
      }
      
      ndt4 <- dt2 %>% filter(block_name %in% c("b5a"))
      if (nrow(ndt4)==0) {
        ndt4
      } else {
        ndt4 <- ndt4 %>% rowwise() %>%
          mutate(bg=bg_de2(c(b5_q,b5_a_1,b5_a_2,b5_a_3,b5_a_4)))
      }
      
       ndt5 <- dt2 %>% filter(block_name %in% c("b5b"))
      if (nrow(ndt4)==0) {
        ndt5
      } else {
        ndt5 <- ndt5 %>% rowwise() %>%
          mutate(bg=bg_de2(c(b5_q,b5_a_1,b5_a_2,b5_a_3,b5_a_4,b5_a_5,b5_a_6)))
      }
  }

  bb <- full_join(dt, bind_rows(ndt1, ndt2, ndt3, ndt4, ndt5))
  bb
}

# 定义单个个体AOI判断与汇总方法
sub_aoi <- function(f_path, out_path, a_path, pb2){
  pb2$tick()$print()
  file <- fread(f_path)
  method <- ifelse("sxp" %in% colnames(file), aj_s,
            ifelse("axp" %in% colnames(file), aj_f, aj_r))
  aoi <- fread(a_path)
  trial_list <- unique(file$trial_name)
  new <- suppressMessages(reduce(future_map(trial_list, trial_name_aoi, ai=aoi, f=file, m=method), suppressMessages(full_join)))
  new <- sub_bg_aoi(new)
  write_csv(new, file=gzfile(out_path))
  gc()
}

# 定义单个目录的AOI批量判断
mul_aoi <- function(in_dir, out_dir){
  if (!dir.exists(out_dir)) {
    dir.create(out_dir)
  }
  out_list <- paste(out_dir,"/",list.files(in_dir), ".gz", sep = "")
  in_list <- paste(in_dir,"/",list.files(in_dir), sep = "")
  a_path <- "/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/tidy/AOI_info_3.csv"
  pb2 <- progress_estimated(length(in_list))
  map2(in_list, out_list, sub_aoi, a_path=a_path, pb2=pb2)
}

```

## 运行函数进行打标并保存

```{r, message=FALSE, warning=FALSE}
raw_d <- "/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/tidy/raw_clean"   
raw_o <- "/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/tidy/raw_clean_aoi"   

saac_d <- "/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/tidy/sacc_clean_re"
saac_o <- "/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/tidy/sacc_clean_re_aoi_multi"

fix_d <- "/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/tidy/fix_clean"
fix_o <- "/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/tidy/fix_clean_aoi"

```

运行函数`mul_aoi(d,o)`对相应数据文件进行批量打标，注意修改`aj()`函数进行匹配。

ceshi
mul_aoi("/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/tidy/test","/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/tidy/test_oo")
