---
title: "数据整理与清洗3"
author: "Chen Xing"
date: '2022-04-17'
output: html_document
---

# 上接数据整理与清洗2
```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(data.table)
```

## 修正眼跳度数数据
根据实验实际情况对眼跳度数进行修正。   
实验显示器宽**37.5***cm* 高**30***cm*，被试距离显示器距离**65***cm*，显示器分辨率**1024** x **768**     
因此求得视角每*度*约**32***像素点*，据此参数进行修正。   

### 定义修正方法
```{r, message=FALSE, warning=FALSE}
sacc_refine <- function(data){
  dt <- fread(data) %>%
    mutate(ampl_re = round(sqrt((sxp-exp)^2 + (syp-eyp)^2)/32,2))
}
```

### 进行修正并保存
```{r, message=FALSE, warning=FALSE}
# 定义处理及保存方法
sacc_refine_save <- function(rdic, sdic){
  if (!dir.exists(sdic)) {
    dir.create(sdic)
  }
  out_list <- paste(sdic,"/",list.files(rdic), sep = "")
  file_list <- paste(rdic,"/",list.files(rdic), sep = "")
  map2(file_list, out_list, ~try(write_excel_csv(sacc_refine(.x), .y)))
  "done"
}

sacc_refine_save("/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/tidy/sacc_clean", "/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/tidy/sacc_clean_re")
```

### 量表信息修正
增加量表得分高低分组信息   
#### 高低分组
```{r, message=FALSE, warning=FALSE}
dt <- read.csv("/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/tidy/scale_sum.csv")
quantile(dt$tgjl,c(0.3,0.7))
quantile(dt$maas,c(0.3,0.7))
quantile(dt$sas,c(0.3,0.7))
dt <- dt %>% mutate(tgjl_g = case_when(tgjl<=34~"low",
                                       tgjl>=42~"high",
                                       tgjl>34&tgjl<42~"mid"),
                  maas_g = case_when(maas<= 41~"low",
                                      maas>=52~"high",
                                      maas<52&maas>41~ "mid"),
                  sas_g =case_when(sas<= 25~"low",
                                   sas>=38~"high",
                                   sas<38&sas>25~"mid")) %>%
  mutate(tgjl_eg = case_when(tgjl_e<=34~"low",
                            tgjl_e>=42~"high",
                            tgjl_e>34&tgjl_e<42~"mid"),
         maas_eg = case_when(maas_e<= 41~"low",
                            maas_e>=52~"high",
                            maas_e<52&maas_e>41~ "mid"),
          sas_eg =case_when(sas_e<= 25~"low",
                           sas_e>=38~"high",
                           sas_e<38&sas_e>25~"mid"))
write_excel_csv(dt, "/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/tidy/scale_sum_r.csv")
```

