---
title: "Static_ana_7"
author: "Chen Xing"
date: '2022-05-03'
output: html_document
---


## 对b4进行 量表得分 x aoi x ab处理 混合重复测量方差分析


### 必要的包
```{r, message=FALSE, warning=FALSE, results='hide', echo=FALSE}
library(tidyverse)
library(rstatix)
library(ggpubr)
```

### 开始分析
#### 数据准备
```{r, message=FALSE, warning=FALSE}
# 数据导入
dt <- read.csv("/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/ea/data/inner_dt_aoi_re.csv")
```

#### fangfa
```{r, message=FALSE, warning=FALSE}
b4test <- function(bname,sname,a,group, metri,dt){
  dtb3 <- dt %>% filter(block_name %in% bname, stim==sname, AOI %in% a) %>%
    mutate(tgroup=!!sym(group)) %>%
    filter(tgroup!="mid") %>%
    group_by(participant_phone, block_name, tgroup, AOI) %>%
    summarise(fc=mean(!!sym(metri), rm.na=T)) %>%
    select(participant_phone, block_name, tgroup, fc, AOI) %>%
    convert_as_factor(participant_phone, block_name, tgroup, AOI) %>% ungroup()
  
  
  dtb3 %>%
    group_by(block_name, tgroup, AOI) %>%
    get_summary_stats(fc, type = "mean_sd")
  
  
  outdata <- dtb3 %>%
    group_by(block_name, tgroup, AOI) %>%
    identify_outliers(fc)
  dtb3_r <- anti_join(dtb3, outdata)
  outdata2 <- dtb3_r %>%
    group_by(block_name, tgroup, AOI) %>%
    identify_outliers(fc)
  dtb3_r2 <- anti_join(dtb3_r, outdata2)
  outdata3 <- dtb3_r2 %>%
    group_by(block_name, tgroup, AOI) %>%
    identify_outliers(fc)
  dtb3_r3 <- anti_join(dtb3_r2, outdata3)
  outdata4 <- dtb3_r3 %>%
    group_by(block_name, tgroup, AOI) %>%
    identify_outliers(fc)
  dtb3_r4 <- anti_join(dtb3_r3, outdata4)
  outdata5 <- dtb3_r4 %>%
    group_by(block_name, tgroup, AOI) %>%
    identify_outliers(fc)
  

  
  ggqqplot(dtb3_r4, "fc", ggtheme = theme_bw()) +
    facet_grid(block_name + tgroup ~ AOI, labeller = "label_both")
  
  dtb3_r4 %>%
    group_by(block_name, AOI) %>%
    levene_test(fc ~ tgroup)
  
  res.aov <- anova_test(
    data = dtb3_r4, dv = fc, wid = participant_phone,
    between = tgroup, within = c(block_name, AOI)
  )
  get_anova_table(res.aov)
  
  bxp <- ggboxplot(
    dtb3_r4, x = "tgroup", y = "fc",
    color = "AOI", palette = "jco",
    facet.by = "block_name", short.panel.labs = FALSE
  )
  bxp
  
  # Two-way ANOVA at each exercises group level
  two.way <- dtb3_r4 %>%
    group_by(tgroup) %>%
    anova_test(dv = fc, wid = participant_phone, within = c(block_name, AOI))
  two.way
  # Extract anova table
  get_anova_table(two.way)
  
  AOI.effect <- dtb3_r4 %>%
    group_by(tgroup, block_name) %>%
    anova_test(dv = fc, wid = participant_phone, within = AOI) %>%
    get_anova_table()
  AOI.effect
  
  
  # compute pairwise comparisons
  pwc <- dtb3_r4 %>%
    group_by(tgroup, block_name) %>%
    pairwise_t_test(
      fc ~ AOI, paired = F, 
      p.adjust.method = "bonferroni"
    )
  # Focus on the results of exercises:yes group
  pwc %>%
    select(-p)    # Remove p column
  
  # Visualization: box plots with p-values
  pwc <- pwc %>% add_xy_position(x = "tgroup")
  pwc.filtered <- pwc
  f1 <- bxp + 
    stat_pvalue_manual(pwc.filtered, tip.length = 0, hide.ns = TRUE) +
    labs(
      subtitle = get_test_label(res.aov, detailed = TRUE),
      caption = get_pwc_label(pwc),
      y = metri
    )
  
  
  bxp2 <- ggboxplot(
    dtb3_r4, x = "AOI", y = "fc",
    color = "tgroup", palette = "jco",
    facet.by = "block_name", short.panel.labs = FALSE
  )
  bxp2
  
  # compute pairwise comparisons
  pwc2 <- dtb3_r4 %>%
    group_by(AOI, block_name) %>%
    pairwise_t_test(
      fc ~ tgroup, paired = F, 
      p.adjust.method = "bonferroni"
    )
  # Focus on the results of exercises:yes group
  pwc2 %>%
    select(-p)    # Remove p column
  
  # Visualization: box plots with p-values
  pwc2 <- pwc2 %>% add_xy_position(x = "AOI")
  pwc.filtered <- pwc2
  f2 <- bxp2 + 
    stat_pvalue_manual(pwc.filtered, tip.length = 0, hide.ns = TRUE) +
    labs(
      subtitle = get_test_label(res.aov, detailed = TRUE),
      caption = get_pwc_label(pwc2),
      y = metri
    )
  
  list(f1,f2)
}

```

#### 参数定义
```{r, message=FALSE, warning=FALSE}
block <- c("b4a", "b4b")
stim <- 1
aoilist <- c("b4_text","bg")
mlist <- c("fc", "afd", "dff", "ffd", "pd", "dw", "asa", "sc", "sad", "asd", "spv")
```


## 文字aoi上的交互 tgjl
```{r, message=FALSE, warning=FALSE}
map(mlist, possibly(b4test, otherwise = NA_character_), dt=dt, bname=block, sname=stim, a=aoilist, group="tgjl_g")
```

## 文字aoi上的交互 maas
```{r, message=FALSE, warning=FALSE}
map(mlist, possibly(b4test, otherwise = NA_character_), dt=dt, bname=block, sname=stim, a=aoilist, group="maas_g")
```

## 文字aoi上的交互 sas
```{r, message=FALSE, warning=FALSE}
map(mlist, possibly(b4test, otherwise = NA_character_), dt=dt, bname=block, sname=stim, a=aoilist, group="sas_g")
```
