---
title: "Static_ana_7"
author: "Chen Xing"
date: '2022-05-03'
output: html_document
---


## 对b4进行 量表得分 x aoi x ab处理 混合重复测量方差分析 中期汇报 版本


### 必要的包
```{r, message=FALSE, warning=FALSE, results='hide', echo=FALSE}
library(tidyverse)
library(rstatix)
library(ggpubr)
```

### 开始分析
#### 数据准备
```{r, message=FALSE, warning=FALSE}
# 数据导入
dt <- read.csv("/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/ea/data/inner_dt_aoi_re.csv")
```

#### fangfa
```{r, message=FALSE, warning=FALSE}
b4test <- function(bname,sname,a, metri,dt){
  dtb3 <- dt %>% filter(block_name %in% bname, stim==sname, AOI %in% a) %>%
    group_by(participant_phone, block_name) %>%
    summarise(fc=mean(!!sym(metri), rm.na=T)) %>%
    select(participant_phone, block_name, fc) %>%
    convert_as_factor(participant_phone, block_name) %>% ungroup()
  
  
  dtb3 %>%
    group_by(block_name) %>%
    get_summary_stats(fc, type = "mean_sd")
  
  
  outdata <- dtb3 %>%
    group_by(block_name) %>%
    identify_outliers(fc)
  dtb3_r <- anti_join(dtb3, outdata)
  outdata2 <- dtb3_r %>%
    group_by(block_name) %>%
    identify_outliers(fc)
  dtb3_r2 <- anti_join(dtb3_r, outdata2)
  outdata3 <- dtb3_r2 %>%
    group_by(block_name) %>%
    identify_outliers(fc)
  dtb3_r3 <- anti_join(dtb3_r2, outdata3)
  outdata4 <- dtb3_r3 %>%
    group_by(block_name) %>%
    identify_outliers(fc)
  dtb3_r4 <- anti_join(dtb3_r3, outdata4)
  outdata5 <- dtb3_r4 %>%
    group_by(block_name) %>%
    identify_outliers(fc)


  
  res.aov <- anova_test(data = dtb3_r4, dv = fc, wid = participant_phone, within = block_name)
  get_anova_table(res.aov)
  
  bxp <- ggboxplot(dtb3_r4, x = "block_name", y = "fc", add = "point")
  bxp
  
  pwc <- dtb3_r4 %>%
  pairwise_t_test(
    fc ~ block_name, paired = TRUE,
    p.adjust.method = "bonferroni"
    )
  pwc
  
  # Visualization: box plots with p-values
  pwc <- pwc %>% add_xy_position(x = "block_name")
  f <- bxp + 
  stat_pvalue_manual(pwc) +
  labs(
    subtitle = get_test_label(res.aov, detailed = TRUE),
    caption = get_pwc_label(pwc),
    y = metri
  )
  
}

```

#### 参数定义
```{r, message=FALSE, warning=FALSE}
block <- c("b4a", "b4b")
stim <- 1
aoilist <- c("b4_text")
mlist <- c("fc", "afd", "dff", "ffd", "pd", "dw", "asa", "sc", "sad", "asd", "spv")
```


## 文字aoi上的交互 tgjl
```{r, message=FALSE, warning=FALSE}
map(mlist, possibly(b4test, otherwise = NA_character_), dt=dt, bname=block, sname=stim, a=aoilist)
```

