---
title: "数据整理与清洗2"
author: "Chen Xing"
date: '2022-04-13'
output: html_document
---

# 上接数据整理与清洗1
```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
library(data.table)
pc <- read_csv("/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/tidy/paichu.csv")
track_loss<- read_csv("/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/tidy/track_loss_trial.csv")
```


## 6. 定义清洗方法
### 定义文件读取方法
```{r, message=FALSE, warning=FALSE}
# 仅读取有效被试数据
read_eye <- function(file){
  dt <- fread(file) %>%
  mutate(participant_phone=as.numeric(participant_phone))
  if (unique(dt$participant_phone[[1]]) %in% pc$participant_phone) {
    return(NA)
  } else
    dt <- filter(dt, !is.na(participant_phone), block !=0, stim !=0)
}
```

### 定义trackloss清洗方法
```{r, message=FALSE, warning=FALSE}
loss_clean <- function(dt){
  loss_info <- filter(track_loss, participant_phone == dt$participant_phone[[1]])
  dt_c <- anti_join(dt, loss_info)
  dt_c
}
```

### 定义时间戳清洗方法
```{r, message=FALSE, warning=FALSE}
# 根据msg文件生成关键时间点信息文件
time_msg <- function(msgfile){
  tt <- pivot_longer(msgfile, cols=c(12,14,16,18,20,22), names_to = "stim", values_to = "start_time", values_drop_na = FALSE) %>% mutate(stim=str_replace(stim, "_start", "")) %>%
    mutate(stim=str_replace(stim, "stim_", ""))
  
  td <- pivot_longer(msgfile, cols=c(13,15,17,19,21,23), names_to = "stim", values_to = "end_time", values_drop_na = FALSE) %>% mutate(stim=str_replace(stim, "_end", "")) %>%
    mutate(stim=str_replace(stim, "stim_", ""))
  
  a <- full_join(tt,td) %>%
    select(participant_group, participant_phone, block, block_name, trial_id, trial_name, type, stim, start_time, end_time) %>% mutate(stim=str_replace(stim, "1_2", "1.5")) %>%
    mutate(stim=as.numeric(stim))
  a
}

tm <- time_msg(read_csv("/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/tidy/msg.csv"))

# 保存关键时间点信息文件
write_excel_csv(tm, "/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/tidy/msg_time.csv")

# 定义时间戳清洗方法
time_clean <- function(rfile){
  k <- tm %>% filter(participant_phone==rfile$participant_phone[[1]]) %>%
  right_join(rfile)
  if ("time" %in% colnames(k)) {
    k <- mutate(k, time_p = time - start_time) %>% select(-start_time, -end_time)
  } else
    k <- mutate(k, stime_p = stime - start_time, etime_p = etime - start_time) %>% select(-start_time, -end_time)
  k
}

```

### 定义清洗处理及保存方法
```{r, message=FALSE, warning=FALSE}
# 合并处理操作
data_clean <- function(d){
  if (is.na(read_eye(d))) {
    "invalid_data"
  } else
    dt <- read_eye(d) %>% loss_clean %>% time_clean
}

# 定义处理及保存方法
raw_clean_save <- function(rdic, sdic){
  if (!dir.exists(sdic)) {
    dir.create(sdic)
  }
  out_list <- paste(sdic,"/",list.files(rdic), sep = "")
  file_list <- paste(rdic,"/",list.files(rdic), sep = "")
  map2(file_list, out_list, ~try(write_excel_csv(data_clean(.x), .y)))
  "done"
}
```

### 进行保存操作
```{r, message=FALSE, warning=FALSE}
# 数据所在目录
dic <- "/Users/placenameday/R study/edf_demo/data/processed/eye_tacking/tidy/"
# 需要处理的文件夹名称
rname <- c("raw", "fix", "sacc", "blinks")
# 合并信息
rlist <- paste(dic, rname, sep = "")
olist <- paste(dic, rname, "_", "clean", sep = "")

# 进行处理及保存
map2(rlist, olist, raw_clean_save)
```
数据清洗完毕