
point_eye <- function(dt, x, y,z){
  e <- ggplot(dt, aes_string(x, y, color=z))
  e + geom_point() + geom_smooth(method = lm) + labs(x=x, y=y)
}

point_eye(b1_eye_event, "maas", "pupil", "block_name")
point_eye(b1_eye_event, "maas", "fix_count", "block_name")
point_eye(b1_eye_event, "maas", "fix_duration", "block_name")
point_eye(b1_eye_event, "maas", "sacc_count", "block_name")
point_eye(b1_eye_event, "maas", "sacc_duration", "block_name")
point_eye(b1_eye_event, "maas", "sacc_ampl", "block_name")
point_eye(b1_eye_event, "maas", "sacc_pv", "block_name")
point_eye(b1_eye_event, "maas", "blinks_count", "block_name")
point_eye(b1_eye_event, "maas", "blinks_duration", "block_name")

point_eye(b1_eye_event, "sas", "pupil", "block_name")
point_eye(b1_eye_event, "sas", "fix_count", "block_name")
point_eye(b1_eye_event, "sas", "fix_duration", "block_name")
point_eye(b1_eye_event, "sas", "sacc_count", "block_name")
point_eye(b1_eye_event, "sas", "sacc_duration", "block_name")
point_eye(b1_eye_event, "sas", "sacc_ampl", "block_name")
point_eye(b1_eye_event, "sas", "sacc_pv", "block_name")
point_eye(b1_eye_event, "sas", "blinks_count", "block_name")
point_eye(b1_eye_event, "sas", "blinks_duration", "block_name")

point_eye(b1_eye_event, "tgjl", "pupil", "block_name")
point_eye(b1_eye_event, "tgjl", "fix_count", "block_name")
point_eye(b1_eye_event, "tgjl", "fix_duration", "block_name")
point_eye(b1_eye_event, "tgjl", "sacc_count", "block_name")
point_eye(b1_eye_event, "tgjl", "sacc_duration", "block_name")
point_eye(b1_eye_event, "tgjl", "sacc_ampl", "block_name")
point_eye(b1_eye_event, "tgjl", "sacc_pv", "block_name")
point_eye(b1_eye_event, "tgjl", "blinks_count", "block_name")
point_eye(b1_eye_event, "tgjl", "blinks_duration", "block_name")

point_eye(b4_eye_event, "tgjl", "pupil", "block_name")
point_eye(b4_eye_event, "tgjl", "fix_count", "block_name")
point_eye(b4_eye_event, "tgjl", "fix_duration", "block_name")
point_eye(b4_eye_event, "tgjl", "sacc_count", "block_name")
point_eye(b4_eye_event, "tgjl", "sacc_duration", "block_name")
point_eye(b4_eye_event, "tgjl", "sacc_ampl", "block_name")
point_eye(b4_eye_event, "tgjl", "sacc_pv", "block_name")
point_eye(b4_eye_event, "tgjl", "blinks_count", "block_name")
point_eye(b4_eye_event, "tgjl", "blinks_duration", "block_name")

point_eye(b4_eye_event, "maas", "pupil", "block_name")
point_eye(b4_eye_event, "maas", "fix_count", "block_name")
point_eye(b4_eye_event, "maas", "fix_duration", "block_name")
point_eye(b4_eye_event, "maas", "sacc_count", "block_name")
point_eye(b4_eye_event, "maas", "sacc_duration", "block_name")
point_eye(b4_eye_event, "maas", "sacc_ampl", "block_name")
point_eye(b4_eye_event, "maas", "sacc_pv", "block_name")
point_eye(b4_eye_event, "maas", "blinks_count", "block_name")
point_eye(b4_eye_event, "maas", "blinks_duration", "block_name")

point_eye(b4_eye_event, "sas", "pupil", "block_name")
point_eye(b4_eye_event, "sas", "fix_count", "block_name")
point_eye(b4_eye_event, "sas", "fix_duration", "block_name")
point_eye(b4_eye_event, "sas", "sacc_count", "block_name")
point_eye(b4_eye_event, "sas", "sacc_duration", "block_name")
point_eye(b4_eye_event, "sas", "sacc_ampl", "block_name")
point_eye(b4_eye_event, "sas", "sacc_pv", "block_name")
point_eye(b4_eye_event, "sas", "blinks_count", "block_name")
point_eye(b4_eye_event, "sas", "blinks_duration", "block_name")

point_eye(b5_eye_event, "sas", "pupil", "participant_group")
point_eye(b5_eye_event, "sas", "fix_count", "participant_group")
point_eye(b5_eye_event, "sas", "fix_duration", "participant_group")
point_eye(b5_eye_event, "sas", "sacc_count", "participant_group")
point_eye(b5_eye_event, "sas", "sacc_duration", "participant_group")
point_eye(b5_eye_event, "sas", "sacc_ampl", "participant_group")
point_eye(b5_eye_event, "sas", "sacc_pv", "participant_group")
point_eye(b5_eye_event, "sas", "blinks_count", "participant_group")
point_eye(b5_eye_event, "sas", "blinks_duration", "participant_group")

point_eye(b5_eye_event, "maas", "pupil", "participant_group")
point_eye(b5_eye_event, "maas", "fix_count", "participant_group")
point_eye(b5_eye_event, "maas", "fix_duration", "participant_group")
point_eye(b5_eye_event, "maas", "sacc_count", "participant_group")
point_eye(b5_eye_event, "maas", "sacc_duration", "participant_group")
point_eye(b5_eye_event, "maas", "sacc_ampl", "participant_group")
point_eye(b5_eye_event, "maas", "sacc_pv", "participant_group")
point_eye(b5_eye_event, "maas", "blinks_count", "participant_group")
point_eye(b5_eye_event, "maas", "blinks_duration", "participant_group")

point_eye(b5_eye_event, "tgjl", "pupil", "participant_group")
point_eye(b5_eye_event, "tgjl", "fix_count", "participant_group")
point_eye(b5_eye_event, "tgjl", "fix_duration", "participant_group")
point_eye(b5_eye_event, "tgjl", "sacc_count", "participant_group")
point_eye(b5_eye_event, "tgjl", "sacc_duration", "participant_group")
point_eye(b5_eye_event, "tgjl", "sacc_ampl", "participant_group")
point_eye(b5_eye_event, "tgjl", "sacc_pv", "participant_group")
point_eye(b5_eye_event, "tgjl", "blinks_count", "participant_group")
point_eye(b5_eye_event, "tgjl", "blinks_duration", "participant_group")